# Objectif : charger les 4 vraies sources D1, D2, D3, D4, vérifier leur structure, les identifiants, les doublons, les valeurs manquantes et surtout déterminer les cohortes réellement disponibles pour M_T0 et M_T1.

# Cellule 1 — Imports et configuration

In [1]:
# ============================================================
# CELLULE 1 — Imports et configuration générale
# ============================================================

from pathlib import Path
import json
import re
import unicodedata

import numpy as np
import pandas as pd

from IPython.display import display

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 220)

print("✅ Environnement prêt")
print("Pandas :", pd.__version__)
print("NumPy  :", np.__version__)

✅ Environnement prêt
Pandas : 2.1.4
NumPy  : 1.26.4

# Cellule 2 — Organisation des dossiers et détection des fichiers

In [2]:
# ============================================================
# CELLULE 2 — Chemins et détection automatique des 4 sources
# ============================================================

# Cas normal : notebook placé dans projet_master/notebooks/
DATA_DIR = Path("../data")

# Si le notebook est directement dans projet_master/
if not DATA_DIR.exists():
    DATA_DIR = Path("./data")

OUTPUT_DIR = Path("../outputs")

if not OUTPUT_DIR.parent.exists():
    OUTPUT_DIR = Path("./outputs")

# Sous-dossier dédié au notebook 00 (comme 01_nettoyage, 02_diagnostic_T0, ...)
OUTPUT_DIR = OUTPUT_DIR / "00_audit"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("DATA_DIR   :", DATA_DIR.resolve())
print("OUTPUT_DIR :", OUTPUT_DIR.resolve())


def trouver_fichier(noms_possibles, motifs=None):
    """
    Cherche d'abord les noms exacts, puis utilise éventuellement
    quelques mots-clés.
    """
    for nom in noms_possibles:
        chemin = DATA_DIR / nom
        if chemin.exists():
            return chemin

    if motifs:
        fichiers = list(DATA_DIR.iterdir())

        for fichier in fichiers:
            nom = fichier.name.lower()

            if all(m.lower() in nom for m in motifs):
                return fichier

    raise FileNotFoundError(
        f"Fichier introuvable.\n"
        f"Noms recherchés : {noms_possibles}\n"
        f"Dossier : {DATA_DIR.resolve()}"
    )


# D1 — Profil / inscriptions
D1_FILE = trouver_fichier(
    [
        "inscriptions(3).json",
        "inscriptions.json"
    ],
    motifs=["inscription"]
)

# D2 — Test initial T0
D2_FILE = trouver_fichier(
    [
        "tests(3).json",
        "tests.json",
        "test_initial.json"
    ],
    motifs=["test"]
)

# D3 — Test intermédiaire T1
D3_FILE = trouver_fichier(
    [
        "mi-test.xlsx",
        "mi_test.xlsx"
    ],
    motifs=["mi", "test"]
)

# D4 — Test final T2
D4_FILE = trouver_fichier(
    [
        "RESULTATS_FINAL_TESTS_PAR_PARCOURS(1).xlsx",
        "RESULTATS_FINAL_TESTS_PAR_PARCOURS.xlsx",
        "tests_finaux.xlsx"
    ],
    motifs=["final"]
)


print("\n✅ 4 sources détectées")
print("D1 :", D1_FILE)
print("D2 :", D2_FILE)
print("D3 :", D3_FILE)
print("D4 :", D4_FILE)

DATA_DIR   : /home/andrycomputer/Documents/Model-eval-pers-elearning/data
OUTPUT_DIR : /home/andrycomputer/Documents/Model-eval-pers-elearning/outputs/00_audit

✅ 4 sources détectées
D1 : ../data/inscriptions.json
D2 : ../data/tests.json
D3 : ../data/mi-test.xlsx
D4 : ../data/RESULTATS_FINAL_TESTS_PAR_PARCOURS.xlsx

# Cellule 3 — Fonction robuste de lecture JSON

In [3]:
# ============================================================
# CELLULE 3 — Fonction robuste de lecture JSON
# ============================================================

def charger_json_table(chemin):
    """
    Charge un fichier JSON sous forme de DataFrame.

    Gère notamment :
    - liste d'objets JSON ;
    - dictionnaire contenant une liste d'objets ;
    - dictionnaire dont chaque valeur est un objet.
    """

    with open(chemin, "r", encoding="utf-8-sig") as f:
        objet = json.load(f)

    # Cas 1 : liste de lignes
    if isinstance(objet, list):
        return pd.json_normalize(objet)

    # Cas 2 : dictionnaire
    if isinstance(objet, dict):

        # Dictionnaire de dictionnaires
        if objet and all(isinstance(v, dict) for v in objet.values()):
            return pd.json_normalize(list(objet.values()))

        # Recherche d'une liste d'enregistrements à l'intérieur
        for cle, valeur in objet.items():

            if (
                isinstance(valeur, list)
                and len(valeur) > 0
                and isinstance(valeur[0], dict)
            ):
                print(f"ℹ️ Données JSON détectées dans la clé : {cle}")
                return pd.json_normalize(valeur)

        # Dictionnaire simple
        return pd.json_normalize(objet)

    raise ValueError(
        f"Structure JSON non reconnue dans {chemin}"
    )


print("✅ Fonction JSON prête")

✅ Fonction JSON prête

# Cellule 4 — Chargement réel de D1, D2, D3 et D4

In [4]:
# ============================================================
# CELLULE 4 — Chargement des quatre sources
# ============================================================

# D1 — Inscriptions
d1 = charger_json_table(D1_FILE)

# D2 — Test initial T0
d2 = charger_json_table(D2_FILE)

# D3 — Test intermédiaire T1
d3_sheets = pd.read_excel(
    D3_FILE,
    sheet_name=None
)

# D4 — Test final T2
d4_sheets = pd.read_excel(
    D4_FILE,
    sheet_name=None
)


print("✅ Toutes les données sont chargées")

print("\n------------------------------")
print("D1 — INSCRIPTIONS")
print("------------------------------")
print("Dimensions :", d1.shape)

print("\n------------------------------")
print("D2 — TEST INITIAL T0")
print("------------------------------")
print("Dimensions :", d2.shape)


print("\n------------------------------")
print("D3 — TEST INTERMÉDIAIRE T1")
print("------------------------------")

for nom_feuille, df in d3_sheets.items():
    print(f"{nom_feuille:20s} : {df.shape}")


print("\n------------------------------")
print("D4 — TEST FINAL T2")
print("------------------------------")

for nom_feuille, df in d4_sheets.items():
    print(f"{nom_feuille:20s} : {df.shape}")

✅ Toutes les données sont chargées

------------------------------
D1 — INSCRIPTIONS
------------------------------
Dimensions : (472, 19)

------------------------------
D2 — TEST INITIAL T0
------------------------------
Dimensions : (315, 25)

------------------------------
D3 — TEST INTERMÉDIAIRE T1
------------------------------
MI-TEST-DA           : (37, 24)
MI-TEST-BI           : (65, 24)
MI-TEST-DS           : (46, 24)
MI-TEST-IA           : (62, 24)

------------------------------
D4 — TEST FINAL T2
------------------------------
FINAL-TEST-DA        : (34, 22)
FINAL-TEST-BI        : (60, 22)
FINAL-TEST-DS        : (48, 22)
FINAL-TEST-IA        : (64, 22)

# Cellule 5 — Aperçu réel des données

In [5]:
# ============================================================
# CELLULE 5 — Aperçu anonymisé des données
# ============================================================

print("=" * 80)
print("D1 — INSCRIPTIONS")
print("=" * 80)

colonnes_masquees = [
    col
    for col in [
        "Title",
        "IDENTIFICATION"
    ]
    if col in d1.columns
]

display(
    d1.drop(
        columns=colonnes_masquees
    ).head()
)

print("\nColonnes D1 :")

for i, col in enumerate(
    d1.columns,
    start=1
):
    print(f"{i:02d}. {col}")


print("\n" + "=" * 80)
print("D2 — TEST INITIAL T0")
print("=" * 80)

display(
    d2.drop(
        columns=[
            c
            for c in ["Identification"]
            if c in d2.columns
        ]
    ).head()
)

print("\nColonnes D2 :")

for i, col in enumerate(
    d2.columns,
    start=1
):
    print(f"{i:02d}. {col}")

================================================================================
D1 — INSCRIPTIONS
================================================================================

,CreatedAt,UpdatedAt,Année de naissance,Genre,Région d'origine,Filière,Niveau d'étude,Statut actuel,Niveau informatique,Niveau Excel,Niveau Power BI,Niveau Python,Niveau IA,Motivation,Objectif pro,Disponibilité,Source info
0,2026-03-31 23:34:20+00:00,None,2007,Masculin,Analamanga,Informatique / Genie logiciel,Licence 2 (L2),Etudiant(e) a plein temps,Intermediaire,Avance,Intermediaire,Intermediaire,Debutant,[Evoluer dans mon poste],Data Scientist,[En semaine - Matin],LinkedIn
1,2026-04-01 00:36:16+00:00,None,20002,Masculin,Atsimo-Atsinanana,Polytechnique / Genie civil / Genie industriel,Master 1 (M1),Diplome(e) en recherche d emploi,Avance,Avance,Avance,Avance,Intermediaire,[Acquerir des competences techniques],Developpeur Python / IA,[En semaine - Apres-midi],Ami(e)
2,2026-04-01 03:01:14+00:00,None,2001,Feminin,Diana,Droit / Sciences politiques,Master 2 (M2),Diplome(e) en recherche d emploi,Aucun,Aucun,Aucun,Aucun,Aucun,"[Ameliorer mon employabilite, Acquerir des co...",Entrepreneur,[En semaine - Matin],Facebook
3,2026-04-01 03:32:24+00:00,None,2003,Masculin,Diana,Autre,Master 2 (M2),Etudiant(e) en fin d etudes,Intermediaire,Intermediaire,Debutant,Intermediaire,Intermediaire,"[Acquerir des competences techniques, Amelior...",Data Scientist,[Flexible],None
4,2026-04-01 06:14:56+00:00,None,2003,Feminin,Analamanga,"EGS - Economie, Gestion & Sociologie",Licence 3 (L3),Diplome(e) en recherche d emploi,Intermediaire,Intermediaire,Aucun,Aucun,Debutant,"[Acquerir des competences techniques, Amelior...",Business Analyst,[Flexible],Facebook

Colonnes D1 :
01. CreatedAt
02. UpdatedAt
03. Title
04. IDENTIFICATION
05. Année de naissance
06. Genre
07. Région d'origine
08. Filière
09. Niveau d'étude
10. Statut actuel
11. Niveau informatique
12. Niveau Excel
13. Niveau Power BI
14. Niveau Python
15. Niveau IA
16. Motivation
17. Objectif pro
18. Disponibilité
19. Source info

================================================================================
D2 — TEST INITIAL T0
================================================================================

,CreatedAt,UpdatedAt,Date du test,Q1 - Resume ventes Excel,Q2 - Import CSV Excel,Q3 - Modele donnees Excel,Q4 - Mauvaise pratique visu Excel,Q5 - 2e grande valeur Excel,Q6 - Mesure vs Colonne DAX,Q7 - CA annee precedente DAX,Q8 - Vue Modele Power BI,Q9 - Acces directeurs regionaux,Q10 - 12 commerciaux 3 indicateurs,Q11 - Bibliotheque CSV Python,Q12 - Overfitting Underfitting,Q13 - Segmentation 50000 clients,Q14 - Deployer modele Python API,Q15 - Valeurs manquantes 30pc,Q16 - Role system prompt LLM,Q17 - Assistant IA PDF financiers,Q18 - Role embedding dans RAG,Q19 - Agent IA selection outil,Q20 - Sortie fiable LLM tableau,Commentaires
0,2026-03-31 17:09:03+00:00,None,2026-03-31 17:09:02+00:00,B. Tableau croise dynamique (TCD),D. Power Query,C. Power Pivot avec relations,A. Courbes pour tendances temporelles,D. RANG(plage;2),D. Mesure ne peut pas utiliser DAX,B. CALCULATE(SUM SAMEPERIODLASTYEAR),C. Ecrire requetes Power Query,E. Je ne sais pas,A. Histogramme empile,B. scikit-learn,B. Erreur matrice de confusion,A. Reseau de neurones recurrent,C. FastAPI ou Flask + joblib ou pickle,B. Remplacer par 0,D. Definir role et contraintes du modele,B. RAG - indexer et recuperer dynamiquement,B. Authentifier utilisateur,B. Ordre dans lequel les outils sont listes,D. JSON structure avec schema defini,None
1,2026-03-31 17:41:49+00:00,None,2026-03-31 17:41:48+00:00,C. Formule SOMME(),B. Copier-coller manuellement,D. Formules RECHERCHEV,D. Graphique 3D explose,B. GRANDE.VALEUR(plage;2),C. Mesure=visualisation Colonne=stockee,B. CALCULATE(SUM SAMEPERIODLASTYEAR),D. Definir relations entre tables,A. Filtrer manuellement les visuels,D. Radar ou tableau matriciel conditionnel,C. pandas,A. Probleme de normalisation,B. K-Means Clustering,C. FastAPI ou Flask + joblib ou pickle,B. Remplacer par 0,A. Connecter a une base de donnees,D. Connaissances integrees du LLM uniquement,D. Transformer texte en vecteurs numeriques,A. Vote aleatoire,C. Augmenter la temperature,None
2,2026-03-31 18:19:08+00:00,None,2026-03-31 18:19:07+00:00,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,None
3,2026-03-31 18:25:08+00:00,None,2026-03-31 18:25:06+00:00,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,None
4,2026-03-31 20:12:55+00:00,None,2026-03-31 20:12:54+00:00,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,None

Colonnes D2 :
01. CreatedAt
02. UpdatedAt
03. Date du test
04. Q1 - Resume ventes Excel
05. Q2 - Import CSV Excel
06. Q3 - Modele donnees Excel
07. Q4 - Mauvaise pratique visu Excel
08. Q5 - 2e grande valeur Excel
09. Q6 - Mesure vs Colonne DAX
10. Q7 - CA annee precedente DAX
11. Q8 - Vue Modele Power BI
12. Q9 - Acces directeurs regionaux
13. Q10 - 12 commerciaux 3 indicateurs
14. Q11 - Bibliotheque CSV Python
15. Q12 - Overfitting Underfitting
16. Q13 - Segmentation 50000 clients
17. Q14 - Deployer modele Python API
18. Q15 - Valeurs manquantes 30pc
19. Q16 - Role system prompt LLM
20. Q17 - Assistant IA PDF financiers
21. Q18 - Role embedding dans RAG
22. Q19 - Agent IA selection outil
23. Q20 - Sortie fiable LLM tableau
24. Commentaires
25. Identification

In [6]:
# Aperçu des feuilles T1

for nom_feuille, df in d3_sheets.items():

    print("\n" + "=" * 80)
    print(f"D3 / T1 — {nom_feuille}")
    print("=" * 80)

    print("Dimensions :", df.shape)

    display(df.head(3))

    print("\nColonnes :")
    print(list(df.columns))

================================================================================
D3 / T1 — MI-TEST-DA
================================================================================
Dimensions : (37, 24)

,IDENTIFICATION,Id,CreatedAt,UpdatedAt,nc_created_by,nc_updated_by,nc_order,nc_row_meta,Title,Qu'exprime le principe GIGO en Data Analysis ?,"Parmi les 4 piliers de la qualite des donnees, lequel est viole quand un email ne contient pas @ ?","Dans le processus ETL, l'etape Transform correspond a quoi ?","Dans Power Query, quelle action doit-on toujours choisir apres avoir selectionne une source de donnees ?",Pourquoi Power Query affiche-t-il uniquement ~1000 lignes dans l'apercu malgre un fichier de 5 millions de lignes ?,Quelle difference fondamentale existe entre Dupliquer et Referencer une requete dans Power Query ?,Pourquoi preferer Supprimer les autres colonnes (Table.SelectColumns) a Supprimer les colonnes (Table.RemoveColumns) ?,"Une colonne Code Postal contient la valeur 06000. Si on la type en Nombre entier, que se passe-t-il ?",Quel est l'ordre correct du workflow dans Power Query ?,"Dans Power Query, a quel moment doit-on typer les colonnes dans la sequence de transformation ?","Dans un modele en etoile Power Pivot, ou se place la table de faits ?",Quelle est la propriete obligatoire d'une cle primaire dans une table de dimension Power Pivot ?,Une direction DIR (avec un espace final) dans la dimension ne correspond pas a DIR dans la table de faits. Quel est l'impact dans Power Pivot ?,"Vous fusionnez (Merge) la table Ventes avec la table Clients dans Power Query. Quelle jointure conserve toutes les lignes de Ventes, meme si un client n'existe pas dans la table Clients ?",Pourquoi le schema en etoile est-il recommande a la place d'une mega-table unique dans Power Pivot ?
0,NaN,16,2026-05-28 09:30:27+00:00,2026-05-30 06:39:26+00:00,NaN,NaN,NaN,NaN,NaN,A) Un outil de nettoyage automatique integre d...,B) Coherence — les donnees se contredisent,A) Recuperer les donnees depuis les sources (C...,A) Cliquer sur Charger pour importer directeme...,B) C'est une limitation de la licence Excel St...,"D) Dupliquer desactive le chargement, Referenc...",A) Table.SelectColumns est plus rapide a ecrire,D) Power Query preserve automatiquement les ze...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DIEG2026-463,17,2026-05-28 11:55:09+00:00,2026-05-29 03:05:12+00:00,NaN,NaN,NaN,NaN,NaN,"C) Garbage In, Garbage Out — des donnees sourc...",A) Completude — il manque des valeurs,"B) Nettoyer, filtrer, enrichir et formater les...",B) Cliquer sur Transformer les donnees pour ou...,B) C'est une limitation de la licence Excel St...,C) Les deux produisent exactement le meme resu...,B) Table.SelectColumns liste uniquement les co...,C) Le zero initial est perdu — la valeur devie...,C) Connecter > Nommer > Filtrer > Supprimer co...,B) Avant chaque operation de nettoyage pour ev...,"C) Au centre, reliee a toutes les tables de di...",D) Elle doit s'appeler ID ou Code par convention,C) La ligne DIR n'a aucune correspondance — se...,A) Inner Join — uniquement les lignes correspo...,A) Parce que Power Pivot ne peut pas charger u...
2,DIEG2026-636,18,2026-05-28 11:56:26+00:00,2026-05-28 12:09:29+00:00,NaN,NaN,NaN,NaN,NaN,"C) Garbage In, Garbage Out — des donnees sourc...",D) Exactitude — la valeur ne represente pas co...,A) Recuperer les donnees depuis les sources (C...,B) Cliquer sur Transformer les donnees pour ou...,C) Il utilise l'evaluation paresseuse (Lazy Ev...,B) Dupliquer cree une copie independante (sour...,B) Table.SelectColumns liste uniquement les co...,C) Le zero initial est perdu — la valeur devie...,C) Connecter > Nommer > Filtrer > Supprimer co...,"C) En toute derniere etape de la requete, apre...","C) Au centre, reliee a toutes les tables de di...",B) Elle doit etre strictement unique — aucun d...,C) La ligne DIR n'a aucune correspondance — se...,D) Full Outer Join — toutes les lignes des deu...,B) Parce que la mega-table duplique les donnee...

Colonnes :
['IDENTIFICATION', 'Id', 'CreatedAt', 'UpdatedAt', 'nc_created_by', 'nc_updated_by', 'nc_order', 'nc_row_meta', 'Title', "Qu'exprime le principe GIGO en Data Analysis ?", 'Parmi les 4 piliers de la qualite des donnees, lequel est viole quand un email ne contient pas @ ?', "Dans le processus ETL, l'etape Transform correspond a quoi ?", 'Dans Power Query, quelle action doit-on toujours choisir apres avoir selectionne une source de donnees ?', "Pourquoi Power Query affiche-t-il uniquement ~1000 lignes dans l'apercu malgre un fichier de 5 millions de lignes ?", 'Quelle difference fondamentale existe entre Dupliquer et Referencer une requete dans Power Query ?', 'Pourquoi preferer Supprimer les autres colonnes (Table.SelectColumns) a Supprimer les colonnes (Table.RemoveColumns) ?', 'Une colonne Code Postal contient la valeur 06000. Si on la type en Nombre entier, que se passe-t-il ?', "Quel est l'ordre correct du workflow dans Power Query ?", 'Dans Power Query, a quel moment doit-on typer les colonnes dans la sequence de transformation ?', 'Dans un modele en etoile Power Pivot, ou se place la table de faits ?', "Quelle est la propriete obligatoire d'une cle primaire dans une table de dimension Power Pivot ?", "Une direction DIR (avec un espace final) dans la dimension ne correspond pas a DIR dans la table de faits. Quel est l'impact dans Power Pivot ?", "Vous fusionnez (Merge) la table Ventes avec la table Clients dans Power Query. Quelle jointure conserve toutes les lignes de Ventes, meme si un client n'existe pas dans la table Clients ?", "Pourquoi le schema en etoile est-il recommande a la place d'une mega-table unique dans Power Pivot ?"]

================================================================================
D3 / T1 — MI-TEST-BI
================================================================================
Dimensions : (65, 24)

,IDENTIFICATION,Id,CreatedAt,UpdatedAt,nc_created_by,nc_updated_by,nc_order,nc_row_meta,Title,Quel niveau d'analyse repond a la question : Que s'est-il passe ?,Lequel de ces ensembles constitue correctement l'ecosysteme Power BI ?,Quel mode de connexion Power BI est recommande dans 95 % des cas en entreprise ?,Un analyste Elite Power BI doit principalement repondre a quelle question ?,"Dans Power Query, l'etape Load du modele ETL correspond a quoi ?",Le Fill Down dans Power Query permet de corriger quel probleme ?,Quelle est la methode recommandee pour l'Unpivot en production (donnees mensuelles) ?,"Dans l'architecture 3 couches Power Query, quel prefixe designe les tables finales chargees dans le modele ?",Pourquoi faut-il imperativement typer la colonne Matricule en Texte (jamais en Nombre) ?,Quel est l'ordre correct des operations lors du nettoyage de cellules fusionnees ?,Quelle cardinalite est standard pour une relation Dimension vers Table de Faits ?,Pourquoi cree-t-on une Dim_Calendrier separee plutot que d'utiliser directement les dates de la table de faits ?,Quelle est la principale raison pour laquelle le modele en etoile est prefere au modele a plat (flat table) dans Power BI ?,Que se passe-t-il automatiquement dans Power BI lorsque la colonne cote 1 d'une relation contient des valeurs en double ?,Comment resoudre correctement une relation plusieurs-a-plusieurs (*:*) entre deux tables dans un modele en etoile ?
0,NaN,17,2026-05-28 09:22:21+00:00,2026-05-30 06:38:22+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,18,2026-05-28 11:03:41+00:00,2026-05-30 06:39:02+00:00,NaN,NaN,NaN,NaN,NaN,C) Descriptif,"B) Power BI Desktop, Service, Mobile et Data G...",C) Import — donnees copiees dans Power BI,C) Pourquoi cela s'est-il passe — et que faut-...,C) L'envoi des donnees propres vers le modele ...,B) Les cellules fusionnees Excel qui deviennen...,C) Selectionner les colonnes stables puis Depi...,B) Stg_ — staging nettoyage (Load desactive),B) Pour eviter la perte des zeros initiaux qui...,C) Trier puis Fill Down puis Supprimer les lig...,C) 1 a plusieurs (1:*),B) Pour permettre l'analyse Annee/Trimestre/Mo...,B) Il reduit la duplication des donnees et opt...,B) La cardinalite bascule automatiquement en p...,C) Creer une table de liaison (Bridge table) c...
2,NaN,19,2026-05-28 11:37:35+00:00,2026-05-30 06:38:59+00:00,NaN,NaN,NaN,NaN,NaN,C) Descriptif,"B) Power BI Desktop, Service, Mobile et Data G...",C) Import — donnees copiees dans Power BI,A) Que s'est-il passe ?,C) L'envoi des donnees propres vers le modele ...,A) Les valeurs en double sur la cle primaire,C) Selectionner les colonnes stables puis Depi...,C) Dim_ / Fact_ — tables finales (Load active),B) Pour eviter la perte des zeros initiaux qui...,C) Trier puis Fill Down puis Supprimer les lig...,C) 1 a plusieurs (1:*),B) Pour permettre l'analyse Annee/Trimestre/Mo...,B) Il reduit la duplication des donnees et opt...,B) La cardinalite bascule automatiquement en p...,B) Supprimer la relation et dupliquer les colo...

Colonnes :
['IDENTIFICATION', 'Id', 'CreatedAt', 'UpdatedAt', 'nc_created_by', 'nc_updated_by', 'nc_order', 'nc_row_meta', 'Title', "Quel niveau d'analyse repond a la question : Que s'est-il passe ?", "Lequel de ces ensembles constitue correctement l'ecosysteme Power BI ?", 'Quel mode de connexion Power BI est recommande dans 95 % des cas en entreprise ?', 'Un analyste Elite Power BI doit principalement repondre a quelle question ?', "Dans Power Query, l'etape Load du modele ETL correspond a quoi ?", 'Le Fill Down dans Power Query permet de corriger quel probleme ?', "Quelle est la methode recommandee pour l'Unpivot en production (donnees mensuelles) ?", "Dans l'architecture 3 couches Power Query, quel prefixe designe les tables finales chargees dans le modele ?", 'Pourquoi faut-il imperativement typer la colonne Matricule en Texte (jamais en Nombre) ?', "Quel est l'ordre correct des operations lors du nettoyage de cellules fusionnees ?", 'Quelle cardinalite est standard pour une relation Dimension vers Table de Faits ?', "Pourquoi cree-t-on une Dim_Calendrier separee plutot que d'utiliser directement les dates de la table de faits ?", 'Quelle est la principale raison pour laquelle le modele en etoile est prefere au modele a plat (flat table) dans Power BI ?', "Que se passe-t-il automatiquement dans Power BI lorsque la colonne cote 1 d'une relation contient des valeurs en double ?", 'Comment resoudre correctement une relation plusieurs-a-plusieurs (*:*) entre deux tables dans un modele en etoile ?']

================================================================================
D3 / T1 — MI-TEST-DS
================================================================================
Dimensions : (46, 24)

,IDENTIFICATION,Id,CreatedAt,UpdatedAt,nc_created_by,nc_updated_by,nc_order,nc_row_meta,Title,Quel type d'analyse repond a la question : Que va-t-il se passer ?,Pourquoi utilise-t-on un environnement virtuel Python (venv) dans un projet Data Science ?,Quelle structure Python permet un acces rapide a une valeur via une cle unique (ex : client[nom]) ?,Laquelle de ces familles represente 80 % des donnees mondiales ?,"Dans le processus E-L (Extract-Load), quelle operation precede le chargement dans Pandas ?","Quelle methode Pandas genere instantanement un resume statistique (moyenne, ecart-type, min, max) pour chaque colonne numerique ?","Dans Pandas, quelle methode combine deux DataFrames selon une cle commune (equivalent d'un JOIN SQL) ?",Quel graphique est le plus adapte pour detecter les valeurs aberrantes (outliers) dans une distribution ?,"Quelle est la formule de normalisation Min-Max qui ramene les donnees dans l'intervalle [0, 1] ?","Le coefficient de correlation de Pearson entre depense publicitaire et ventes vaut 0,92. Quelle est la bonne interpretation ?",Quelle est la difference fondamentale entre l'apprentissage supervise et non supervise ?,Un modele obtient 99 % de precision sur les donnees d'entrainement mais seulement 62 % sur les donnees de test. De quoi s'agit-il ?,Quelle proportion standard est utilisee pour diviser un jeu de donnees en ensemble d'entrainement et ensemble de test ?,Vous avez 10 000 clients : 9 500 non churn et 500 churn. Quelle technique corrige ce desequilibre sans perdre d'information ?,Pourquoi le Random Forest est-il plus robuste a l'overfitting qu'un arbre de decision unique ?
0,DIEG2026-085,16,2026-05-28 12:12:03+00:00,2026-05-28 12:20:32+00:00,NaN,NaN,NaN,NaN,NaN,C) Predictive,B) Pour isoler les dependances et eviter les c...,C) Dictionnaire {cle: valeur},"C) Donnees non structurees (images, texte libr...","C) L'extraction depuis la source (fichier, bas...",A) df.describe(),C) pd.merge(),D) Boxplot,B) (x - min) / (max - min),C) Il existe une forte liaison lineaire positi...,A) Le supervise est plus rapide que le non sup...,C) Bonne generalisation — un ecart de 37 % est...,D) 60 % entrainement / 40 % test,A) Undersampling — supprimer des exemples de l...,A) Car il utilise uniquement les donnees de te...
1,DIEG2026-148,17,2026-05-28 12:27:58+00:00,2026-05-28 12:35:41+00:00,NaN,NaN,NaN,NaN,NaN,C) Predictive,B) Pour isoler les dependances et eviter les c...,C) Dictionnaire {cle: valeur},"C) Donnees non structurees (images, texte libr...","C) L'extraction depuis la source (fichier, bas...",A) df.describe(),C) pd.merge(),D) Boxplot,B) (x - min) / (max - min),C) Il existe une forte liaison lineaire positi...,B) Le supervise utilise des donnees etiquetees...,B) Overfitting — le modele a memorise les donn...,C) 70-80 % entrainement / 20-30 % test,B) Oversampling manuel — copier des exemples d...,B) Car il combine plusieurs arbres entraines s...
2,NaN,18,2026-05-28 12:29:53+00:00,2026-05-29 13:53:51+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Colonnes :
['IDENTIFICATION', 'Id', 'CreatedAt', 'UpdatedAt', 'nc_created_by', 'nc_updated_by', 'nc_order', 'nc_row_meta', 'Title', "Quel type d'analyse repond a la question : Que va-t-il se passer ?", 'Pourquoi utilise-t-on un environnement virtuel Python (venv) dans un projet Data Science ?', 'Quelle structure Python permet un acces rapide a une valeur via une cle unique (ex : client[nom]) ?', 'Laquelle de ces familles represente 80 % des donnees mondiales ?', 'Dans le processus E-L (Extract-Load), quelle operation precede le chargement dans Pandas ?', 'Quelle methode Pandas genere instantanement un resume statistique (moyenne, ecart-type, min, max) pour chaque colonne numerique ?', "Dans Pandas, quelle methode combine deux DataFrames selon une cle commune (equivalent d'un JOIN SQL) ?", 'Quel graphique est le plus adapte pour detecter les valeurs aberrantes (outliers) dans une distribution ?', "Quelle est la formule de normalisation Min-Max qui ramene les donnees dans l'intervalle [0, 1] ?", 'Le coefficient de correlation de Pearson entre depense publicitaire et ventes vaut 0,92. Quelle est la bonne interpretation ?', "Quelle est la difference fondamentale entre l'apprentissage supervise et non supervise ?", "Un modele obtient 99 % de precision sur les donnees d'entrainement mais seulement 62 % sur les donnees de test. De quoi s'agit-il ?", "Quelle proportion standard est utilisee pour diviser un jeu de donnees en ensemble d'entrainement et ensemble de test ?", "Vous avez 10 000 clients : 9 500 non churn et 500 churn. Quelle technique corrige ce desequilibre sans perdre d'information ?", "Pourquoi le Random Forest est-il plus robuste a l'overfitting qu'un arbre de decision unique ?"]

================================================================================
D3 / T1 — MI-TEST-IA
================================================================================
Dimensions : (62, 24)

,IDENTIFICATION,Id,CreatedAt,UpdatedAt,nc_created_by,nc_updated_by,nc_order,nc_row_meta,Title,Pourquoi un LLM hallucine-t-il meme quand on lui dit : donne uniquement des informations vraies ?,Une information critique est placee au milieu d'un document de 80 pages envoye a un LLM. Quel phenomene reduit la probabilite qu'elle soit bien prise en compte ?,Quelle technique de Prompt Engineering demande au modele de raisonner etape par etape avant de fournir sa reponse finale ?,Vous construisez un classificateur automatique de transactions financieres dans Open WebUI. Quelle valeur de temperature choisir pour des resultats coherents et reproductibles ?,"Pour integrer un LLM dans une application et parser sa reponse automatiquement, quelle methode est la plus robuste ?","Parmi les 6 composantes d'un systeme prompt professionnel, laquelle definit explicitement ce que l'IA ne doit jamais faire ?","Dans Open WebUI, vous configurez le systeme prompt dans Workspace > Models. Quelle taille optimale garantit efficacite sans surcharger le contexte ?","Dans Open WebUI, quelle est la difference fondamentale entre un Skill et le System Prompt configure dans un modele ?","Selon la regle des 50 %, quelle information devrait aller dans un Skill dedie plutot que dans le System Prompt general ?","Dans Open WebUI, vous attachez un Tool Python a votre modele. Quel est l'avantage concret par rapport a un simple Skill textuel ?",Que signifie MCP et quel est son role dans l'ecosysteme IA ?,"Dans la formation, qu'est-ce qu'Antigravity ?",Comment Antigravity peut-il creer et declencher un workflow N8N sans acceder manuellement a l'interface graphique de N8N ?,Un etudiant veut creer un assistant qui repond aux questions sur un document PDF de 300 pages. Quelle architecture choisir ?,"Dans un pipeline RAG, a quoi servent precisement les embeddings ?"
0,DIEG2026-030,16,2026-05-28 11:55:57+00:00,2026-05-28 18:22:15+00:00,NaN,NaN,NaN,NaN,NaN,C) Parce qu'il predit le token suivant le plus...,C) Le Lost in the Middle — les LLMs retiennent...,B) Role Prompting — assigner un role expert au...,A) temperature = 1.5 — pour maximiser la diver...,D) Function Calling / Tool Use — l'API force l...,D) Garde-fous et interdictions — les comportem...,D) La taille n'a aucun impact sur la qualite d...,B) Le System Prompt est charge automatiquement...,B) La devise utilisee (ex : MGA) et le taux de...,D) Le Tool Python accelere la generation de to...,C) Model Context Protocol — standard universel...,B) L'environnement de developpement IA (Claude...,C) Via le MCP Server N8N (mcp-n8n) — Antigravi...,"C) RAG — decouper le PDF en chunks, vectoriser...",C) A transformer chaque chunk de texte en vect...
1,DIEG2026-564,17,2026-05-28 14:05:50+00:00,2026-05-28 14:21:47+00:00,NaN,NaN,NaN,NaN,NaN,C) Parce qu'il predit le token suivant le plus...,C) Le Lost in the Middle — les LLMs retiennent...,C) Chain-of-Thought (CoT) — Reflechis etape pa...,D) temperature = 0 — le modele choisit toujour...,D) Function Calling / Tool Use — l'API force l...,D) Garde-fous et interdictions — les comportem...,B) 200 a 500 mots — assez detaille pour etre p...,B) Le System Prompt est charge automatiquement...,B) La devise utilisee (ex : MGA) et le taux de...,C) Le Tool Python permet au LLM d'obtenir des ...,C) Model Context Protocol — standard universel...,B) L'environnement de developpement IA (Claude...,C) Via le MCP Server N8N (mcp-n8n) — Antigravi...,"C) RAG — decouper le PDF en chunks, vectoriser...",C) A transformer chaque chunk de texte en vect...
2,DIEG2026-460,18,2026-05-28 14:15:12+00:00,2026-05-28 14:26:43+00:00,NaN,NaN,NaN,NaN,NaN,C) Parce qu'il predit le token suivant le plus...,C) Le Lost in the Middle — les LLMs retiennent...,B) Role Prompting — assigner un role expert au...,A) temperature = 1.5 — pour maximiser la diver...,D) Function Calling / Tool Use — l'API force l...,D) Garde-fous et interdictions — les comportem...,C) 2 000 a 5 000 mots — plus le system prompt ...,D) Le Skill fonctionne uniquement avec des mod...,D) Les interdictions permanentes valables dans...,B) Le Tool Python traduit automatiquement les ...,C) Model Context Protocol — standard universel...,B) L'environnement de developpement IA (Claude...,C) Via le MCP Server N8N (mcp-n8n) — Antigravi...,"C) RAG — decouper le PDF en chunks, vectoriser...",C) A transformer chaque chunk de texte en vect...

Colonnes :
['IDENTIFICATION', 'Id', 'CreatedAt', 'UpdatedAt', 'nc_created_by', 'nc_updated_by', 'nc_order', 'nc_row_meta', 'Title', 'Pourquoi un LLM hallucine-t-il meme quand on lui dit : donne uniquement des informations vraies ?', "Une information critique est placee au milieu d'un document de 80 pages envoye a un LLM. Quel phenomene reduit la probabilite qu'elle soit bien prise en compte ?", 'Quelle technique de Prompt Engineering demande au modele de raisonner etape par etape avant de fournir sa reponse finale ?', 'Vous construisez un classificateur automatique de transactions financieres dans Open WebUI. Quelle valeur de temperature choisir pour des resultats coherents et reproductibles ?', 'Pour integrer un LLM dans une application et parser sa reponse automatiquement, quelle methode est la plus robuste ?', "Parmi les 6 composantes d'un systeme prompt professionnel, laquelle definit explicitement ce que l'IA ne doit jamais faire ?", 'Dans Open WebUI, vous configurez le systeme prompt dans Workspace > Models. Quelle taille optimale garantit efficacite sans surcharger le contexte ?', 'Dans Open WebUI, quelle est la difference fondamentale entre un Skill et le System Prompt configure dans un modele ?', 'Selon la regle des 50 %, quelle information devrait aller dans un Skill dedie plutot que dans le System Prompt general ?', "Dans Open WebUI, vous attachez un Tool Python a votre modele. Quel est l'avantage concret par rapport a un simple Skill textuel ?", "Que signifie MCP et quel est son role dans l'ecosysteme IA ?", "Dans la formation, qu'est-ce qu'Antigravity ?", "Comment Antigravity peut-il creer et declencher un workflow N8N sans acceder manuellement a l'interface graphique de N8N ?", 'Un etudiant veut creer un assistant qui repond aux questions sur un document PDF de 300 pages. Quelle architecture choisir ?', 'Dans un pipeline RAG, a quoi servent precisement les embeddings ?']

In [7]:
# Aperçu des feuilles T2

for nom_feuille, df in d4_sheets.items():

    print("\n" + "=" * 80)
    print(f"D4 / T2 — {nom_feuille}")
    print("=" * 80)

    print("Dimensions :", df.shape)

    display(df.head(3))

    print("\nColonnes :")
    print(list(df.columns))

================================================================================
D4 / T2 — FINAL-TEST-DA
================================================================================
Dimensions : (34, 22)

,RowId,CreatedAt,UpdatedAt,InscriptionId,IDENTIFICATION,Filiere,Niveau d'Etude,"Dans Power Query, une colonne Date_Commande contient des dates au format texte. Le tri chronologique ne fonctionne pas. Quelle action corrige le probleme a la source ?",Une table de suivi contient des cellules null dans la colonne Statut. Vous voulez mettre A traiter seulement dans les cellules vides. Quelle transformation appliquer ?,"Vous avez une table Ventes(CodeClient, Montant) et une table Clients(CodeClient, Region). Pour analyser les ventes par Region, quelle operation Power Query est la plus juste ?","Dans Power Query, vous devez creer une colonne Priorite : Haute si Retard_Jours > 7, sinon Normale. Quel outil utiliser ?","Dans un modele Power Pivot de facturation, quelle table doit contenir les lignes avec Montant, Quantite, DateId et ClientId ?",Une table Agences contient une ligne par agence. La table Transactions contient plusieurs lignes par agence. Quelle relation est attendue ?,Vous devez stocker une categorie Age_Classe calculee pour chaque client. Quel objet DAX convient le mieux ?,Quelle mesure DAX compte le nombre de lignes dans la table Reclamations ?,Vous calculez Taux_Reussite = [Admis] / [Inscrits]. Quelle fonction evite une erreur si [Inscrits] est zero ?,Vous avez [Total Montant] et une dimension Filiere reliee aux faits. Quelle formule renvoie le total de la filiere Informatique ?,"Pour montrer l'evolution hebdomadaire du nombre d'inscriptions pendant trois mois, quel graphique est le plus adapte ?",Un tableau de bord Excel contient 4 TCD. Vous voulez filtrer tous les TCD par Niveau d'etude avec un bouton visuel. Quel outil utiliser ?,Vous comparez Objectif et Realise par departement. Quel graphique facilite la comparaison cote a cote ?,"Avant de construire un dashboard sur les abandons de formation, quelle etape vient en premier ?",Un taux global de presence est faible. Quelle attitude est la plus professionnelle ?
0,56,2026-06-06 17:08:28+00:00,2026-06-06 17:21:01+00:00,55,DIEG2026-055,IST - Informatique & Sciences des Technologies,Licence 2 (L2),D) Changer le type de la colonne en Date avec ...,B) Remplacer les valeurs null par A traiter da...,D) Fusionner sur CodeClient puis developper Re...,B) Colonne conditionnelle,B) Fact_Factures,D) Agences 1 vers Transactions plusieurs,A) Une colonne calculee,A) Nb = COUNTROWS(Reclamations),"A) IF([Inscrits] = 0, 0, [Admis] / [Inscrits])...","A) CALCULATE(Filiere[Nom] = ""Informatique"", [T...",A) Barres groupees par filiere et par semaine,B) Filtre automatique applique a la source ava...,B) Barres empilees a 100 % pour voir les propo...,A) Lister les visuels possibles,B) Exclure les absences non justifiees pour re...
1,28,2026-06-04 21:08:44+00:00,2026-06-05 13:37:19+00:00,117,DIEG2026-117,"EGS - Economie, Gestion & Sociologie",Licence 1 (L1),A) Trier la colonne manuellement avant chaque ...,B) Remplacer les valeurs null par A traiter da...,C) Creer une relation sans importer Region dan...,C) Colonne a partir d'exemples avec quelques c...,D) Une table produit avec une ligne par facture,D) Agences 1 vers Transactions plusieurs,D) Un segment cree avant la colonne,B) Nb = COUNT(Reclamations[Id]) si Id est touj...,C) [Admis] / DISTINCTCOUNT(Etudiants[Id]),"C) CALCULATE([Total Montant], Filiere[Nom] = ""...",C) Courbe,D) Filtre de rapport regle separement dans cha...,C) Deux graphiques separes avec la meme echelle,A) Lister les visuels possibles,B) Exclure les absences non justifiees pour re...
2,43,2026-06-05 07:52:11+00:00,2026-06-05 07:59:18+00:00,195,DIEG2026-195,"EGS - Economie, Gestion & Sociologie",Licence 2 (L2),A) Trier la colonne manuellement avant chaque ...,A) Filtrer les lignes null puis les saisir dan...,C) Creer une relation sans importer Region dan...,B) Colonne conditionnelle,C) Une table calendrier contenant aussi les mo...,A) Transactions 1 vers Agences 1 si les noms d...,C) Une mesure car elle change selon le visuel,B) Nb = COUNT(Reclamations[Id]) si Id est touj...,B) CALCULATE([Admis] / [Inscrits]) sans autre ...,"C) CALCULATE([Total Montant], Filiere[Nom] = ""...",C) Courbe,A) Segment connecte aux TCD,A) Barres groupees,A) Lister les visuels possibles,"A) Segmenter par groupe, periode et module ava..."

Colonnes :
['RowId', 'CreatedAt', 'UpdatedAt', 'InscriptionId', 'IDENTIFICATION', 'Filiere', "Niveau d'Etude", 'Dans Power Query, une colonne Date_Commande contient des dates au format texte. Le tri chronologique ne fonctionne pas. Quelle action corrige le probleme a la source ?', 'Une table de suivi contient des cellules null dans la colonne Statut. Vous voulez mettre A traiter seulement dans les cellules vides. Quelle transformation appliquer ?', 'Vous avez une table Ventes(CodeClient, Montant) et une table Clients(CodeClient, Region). Pour analyser les ventes par Region, quelle operation Power Query est la plus juste ?', 'Dans Power Query, vous devez creer une colonne Priorite : Haute si Retard_Jours > 7, sinon Normale. Quel outil utiliser ?', 'Dans un modele Power Pivot de facturation, quelle table doit contenir les lignes avec Montant, Quantite, DateId et ClientId ?', 'Une table Agences contient une ligne par agence. La table Transactions contient plusieurs lignes par agence. Quelle relation est attendue ?', 'Vous devez stocker une categorie Age_Classe calculee pour chaque client. Quel objet DAX convient le mieux ?', 'Quelle mesure DAX compte le nombre de lignes dans la table Reclamations ?', 'Vous calculez Taux_Reussite = [Admis] / [Inscrits]. Quelle fonction evite une erreur si [Inscrits] est zero ?', 'Vous avez [Total Montant] et une dimension Filiere reliee aux faits. Quelle formule renvoie le total de la filiere Informatique ?', "Pour montrer l'evolution hebdomadaire du nombre d'inscriptions pendant trois mois, quel graphique est le plus adapte ?", "Un tableau de bord Excel contient 4 TCD. Vous voulez filtrer tous les TCD par Niveau d'etude avec un bouton visuel. Quel outil utiliser ?", 'Vous comparez Objectif et Realise par departement. Quel graphique facilite la comparaison cote a cote ?', 'Avant de construire un dashboard sur les abandons de formation, quelle etape vient en premier ?', 'Un taux global de presence est faible. Quelle attitude est la plus professionnelle ?']

================================================================================
D4 / T2 — FINAL-TEST-BI
================================================================================
Dimensions : (60, 22)

,RowId,CreatedAt,UpdatedAt,InscriptionId,IDENTIFICATION,Filiere,Niveau d'Etude,Une source contient des lignes Total et des en-tetes repetes. Que risque-t-on si elles restent dans le modele Power BI ?,Un champ Matricule contient 00125. Quel type choisir dans Power Query pour garder la valeur exacte ?,"Une table a les colonnes Produit, Jan, Fev, Mar. Vous voulez filtrer par mois dans Power BI. Quelle transformation faire ?",Une colonne Code contient MG-TNR-2026. Vous voulez recuperer TNR dans une nouvelle colonne. Quelle action est adaptee ?,"Avant un Merge entre Ventes et Produits, quelle verification evite des lignes sans correspondance ?",Pourquoi construire un modele en etoile au lieu d'une seule table plate quand le projet grandit ?,"Apres avoir relie Dim_Produit a Fact_Ventes, quel controle est essentiel ?",Vous devez calculer un taux de marge qui change avec les filtres Region et Produit. Quel objet DAX choisir ?,"Quelle fonction DAX sert a recalculer une mesure dans un contexte filtre, par exemple Annee = 2026 ?","Vous classez les ventes en Faible, Moyen, Fort selon plusieurs seuils. Quelle structure rend souvent le DAX plus lisible ?","Dans un rapport de direction, une bonne visualisation doit surtout :",Pourquoi tester les interactions et filtres avant de publier un rapport ?,Un graphique utilise deux couleurs presque identiques pour deux categories importantes. Quel est le risque ?,Quel visuel est le plus adapte pour comparer Realise vs Objectif par commercial ?,Quelle sequence est la plus professionnelle pour construire une page Power BI ?
0,42,2026-06-05 09:13:19+00:00,2026-06-05 09:22:41+00:00,8,DIEG2026-008,"EGS - Economie, Gestion & Sociologie",Master 2 (M2),B) Des mesures fausses car ces lignes peuvent ...,B) Texte,"C) Depivoter Jan, Fev, Mar en Mois/Valeur",C) Extraire le texte entre delimitateurs,"B) Verifier cle commune, type et espaces inutiles","B) Pour eviter la duplication, clarifier les r...","D) Cardinalite, direction de filtre et unicite...",B) Mesure,A) CALCULATE,"D) SWITCH(TRUE(), ...)","A) Faire ressortir tendances, ecarts et priorites",D) Pour garantir que les chiffres restent cohe...,C) L'utilisateur peut confondre les categories...,C) Barres groupees,"A) Besoins/KPI, modele fiable, choix des visue..."
1,51,2026-06-05 10:46:39+00:00,2026-06-05 10:54:03+00:00,22,DIEG2026-022,"EGS - Economie, Gestion & Sociologie",Licence 3 (L3),D) Un doublon uniquement visible dans la vue D...,D) Nombre decimal,"C) Depivoter Jan, Fev, Mar en Mois/Valeur",A) Fractionner en lignes par delimiteur,D) Fusionner apres avoir supprime la cle,D) Pour remplacer toutes les mesures par colon...,"D) Cardinalite, direction de filtre et unicite...",B) Mesure,A) CALCULATE,"D) SWITCH(TRUE(), ...)",D) Limiter les filtres visibles pour garder un...,D) Pour garantir que les chiffres restent cohe...,D) Le graphique se desactive automatiquement s...,D) Deux cartes KPI globales Realise et Objectif,"D) Importer, colorer, publier, puis definir le..."
2,65,2026-06-05 12:59:24+00:00,2026-06-05 13:14:22+00:00,26,DIEG2026-026,Autre,Licence 3 (L3),NaN,A) Nombre entier avec format 00000,NaN,C) Extraire le texte entre delimitateurs,"B) Verifier cle commune, type et espaces inutiles","B) Pour eviter la duplication, clarifier les r...","D) Cardinalite, direction de filtre et unicite...",B) Mesure,A) CALCULATE,"D) SWITCH(TRUE(), ...)","A) Faire ressortir tendances, ecarts et priorites",D) Pour garantir que les chiffres restent cohe...,D) Le graphique se desactive automatiquement s...,B) Courbe avec les commerciaux en axe des cate...,"D) Importer, colorer, publier, puis definir le..."

Colonnes :
['RowId', 'CreatedAt', 'UpdatedAt', 'InscriptionId', 'IDENTIFICATION', 'Filiere', "Niveau d'Etude", 'Une source contient des lignes Total et des en-tetes repetes. Que risque-t-on si elles restent dans le modele Power BI ?', 'Un champ Matricule contient 00125. Quel type choisir dans Power Query pour garder la valeur exacte ?', 'Une table a les colonnes Produit, Jan, Fev, Mar. Vous voulez filtrer par mois dans Power BI. Quelle transformation faire ?', 'Une colonne Code contient MG-TNR-2026. Vous voulez recuperer TNR dans une nouvelle colonne. Quelle action est adaptee ?', 'Avant un Merge entre Ventes et Produits, quelle verification evite des lignes sans correspondance ?', "Pourquoi construire un modele en etoile au lieu d'une seule table plate quand le projet grandit ?", 'Apres avoir relie Dim_Produit a Fact_Ventes, quel controle est essentiel ?', 'Vous devez calculer un taux de marge qui change avec les filtres Region et Produit. Quel objet DAX choisir ?', 'Quelle fonction DAX sert a recalculer une mesure dans un contexte filtre, par exemple Annee = 2026 ?', 'Vous classez les ventes en Faible, Moyen, Fort selon plusieurs seuils. Quelle structure rend souvent le DAX plus lisible ?', 'Dans un rapport de direction, une bonne visualisation doit surtout :', 'Pourquoi tester les interactions et filtres avant de publier un rapport ?', 'Un graphique utilise deux couleurs presque identiques pour deux categories importantes. Quel est le risque ?', 'Quel visuel est le plus adapte pour comparer Realise vs Objectif par commercial ?', 'Quelle sequence est la plus professionnelle pour construire une page Power BI ?']

================================================================================
D4 / T2 — FINAL-TEST-DS
================================================================================
Dimensions : (48, 22)

,RowId,CreatedAt,UpdatedAt,InscriptionId,IDENTIFICATION,Filiere,Niveau d'Etude,"Dans un TP churn, quel est le premier objectif du Data Scientist apres avoir charge le CSV ?",Une serie de ventes a une tendance visible. Pourquoi verifier ou traiter la stationnarite avant certains modeles temporels ?,"Un modele de prediction utilise age, revenu, anciennete et statut client. Quel format de donnees est principalement traite ?","Avec pandas, quelle etape permet de voir rapidement moyenne, quartiles et dispersion des colonnes numeriques ?","Pour reperer des outliers sur une variable Montant, quel graphique est le plus direct ?","Pour evaluer une prediction de prix ou de chiffre d'affaires, quel indicateur correspond a une regression ?",Pourquoi faire une selection de variables avant l'entrainement ?,"Un coefficient de silhouette de 0,58 sur un clustering client indique generalement :",Vous voulez projeter des profils clients complexes en 2D en gardant des voisinages non lineaires. Quelle methode convient ?,Vous detectez des transactions atypiques sans etiquette fraude/non fraude. Quel type d'apprentissage est le plus probable ?,"Dans train_test_split, quel parametre conserve les proportions des classes dans train et test ?",Pourquoi utiliser GridSearchCV ou RandomizedSearchCV dans un TP ML ?,"Vous testez l'association entre Genre et Churn, deux variables qualitatives. Quel test est adapte ?",Quel algorithme existe en version classification et regression dans scikit-learn ?,"Dans CRISP-DM, avant de modeliser, que doit-on clarifier ?"
0,36,2026-06-05 06:25:52+00:00,2026-06-05 06:35:39+00:00,25,DIEG2026-025,"EGS - Economie, Gestion & Sociologie",Master 2 (M2),A) Comprendre les variables et transformer les...,A) Pour rendre les donnees directement compara...,D) Donnees tabulaires structurees,B) df.describe(),D) Boxplot,A) R2 ajuste,A) Reduire le bruit et aider le modele a gener...,B) Des groupes assez coherents et separes,D) t-SNE,C) Non supervise,A) random_state,B) Tester plusieurs hyperparametres et choisir...,D) Khi-deux ou Fisher selon les effectifs,B) Random Forest,"C) Objectif metier, donnees disponibles et pre..."
1,21,2026-06-04 20:51:48+00:00,2026-06-04 21:00:25+00:00,40,DIEG2026-040,"EGS - Economie, Gestion & Sociologie",Master 1 (M1),A) Comprendre les variables et transformer les...,D) Pour stabiliser les proprietes statistiques...,D) Donnees tabulaires structurees,B) df.describe(),D) Boxplot,A) R2 ajuste,A) Reduire le bruit et aider le modele a gener...,B) Des groupes assez coherents et separes,B) UMAP/PCA sans tenir compte des voisinages,C) Non supervise,B) stratify,B) Tester plusieurs hyperparametres et choisir...,D) Khi-deux ou Fisher selon les effectifs,B) Random Forest,"C) Objectif metier, donnees disponibles et pre..."
2,38,2026-06-05 06:36:26+00:00,2026-06-05 06:46:07+00:00,45,DIEG2026-045,"EGS - Economie, Gestion & Sociologie",Master 1 (M1),A) Comprendre les variables et transformer les...,A) Pour rendre les donnees directement compara...,D) Donnees tabulaires structurees,B) df.describe(),D) Boxplot,A) R2 ajuste,A) Reduire le bruit et aider le modele a gener...,NaN,D) t-SNE,C) Non supervise,A) random_state,C) Remplacer la separation train/test,D) Khi-deux ou Fisher selon les effectifs,B) Random Forest,D) Choix du modele final et hyperparametres de...

Colonnes :
['RowId', 'CreatedAt', 'UpdatedAt', 'InscriptionId', 'IDENTIFICATION', 'Filiere', "Niveau d'Etude", 'Dans un TP churn, quel est le premier objectif du Data Scientist apres avoir charge le CSV ?', 'Une serie de ventes a une tendance visible. Pourquoi verifier ou traiter la stationnarite avant certains modeles temporels ?', 'Un modele de prediction utilise age, revenu, anciennete et statut client. Quel format de donnees est principalement traite ?', 'Avec pandas, quelle etape permet de voir rapidement moyenne, quartiles et dispersion des colonnes numeriques ?', 'Pour reperer des outliers sur une variable Montant, quel graphique est le plus direct ?', "Pour evaluer une prediction de prix ou de chiffre d'affaires, quel indicateur correspond a une regression ?", "Pourquoi faire une selection de variables avant l'entrainement ?", 'Un coefficient de silhouette de 0,58 sur un clustering client indique generalement :', 'Vous voulez projeter des profils clients complexes en 2D en gardant des voisinages non lineaires. Quelle methode convient ?', "Vous detectez des transactions atypiques sans etiquette fraude/non fraude. Quel type d'apprentissage est le plus probable ?", 'Dans train_test_split, quel parametre conserve les proportions des classes dans train et test ?', 'Pourquoi utiliser GridSearchCV ou RandomizedSearchCV dans un TP ML ?', "Vous testez l'association entre Genre et Churn, deux variables qualitatives. Quel test est adapte ?", 'Quel algorithme existe en version classification et regression dans scikit-learn ?', 'Dans CRISP-DM, avant de modeliser, que doit-on clarifier ?']

================================================================================
D4 / T2 — FINAL-TEST-IA
================================================================================
Dimensions : (64, 22)

,RowId,CreatedAt,UpdatedAt,InscriptionId,IDENTIFICATION,Filiere,Niveau d'Etude,"Dans le TP pipeline data, un fichier CSV est depose puis un rapport doit etre disponible dans l'application. Quelle sequence de pipeline est la plus correcte ?","Dans un schema en etoile construit pour les rapports, que contient la table de faits ?","Dans Open WebUI, vous devez rendre une consigne reutilisable pour un modele. Ou cree-t-on un Skill ?","Dans Open WebUI, vous ajoutez un serveur MCP pour exposer des outils externes au modele. Quel espace utiliser ?","Dans une fonction Python Open WebUI de type Pipe ou Filter, ou ajoute-t-on le code ?","Dans FastAPI, pourquoi definir des schemas Pydantic pour les requetes du pipeline ?",Pourquoi Plotly a ete utilise dans le pipeline Python de rapport ?,"Dans la stack pratique, quel role joue Directus ?",La collection session de Directus sert principalement a stocker :,"Dans Next.js, pourquoi consommer l'API Directus ou FastAPI ?","Dans n8n, comment est structure un workflow d'automatisation ?",Un workflow n8n declenche par un upload doit automatiser quoi dans le TP ?,Quel est l'interet d'Antigravity dans le contexte du TP n8n/API ?,"Si Next.js affiche un rapport vide alors que Directus contient la session, quelle verification est prioritaire ?","Dans Open WebUI, pour ajouter un fournisseur LLM comme OpenAI/Ollama/OpenRouter, quelle zone est la plus adaptee ?"
0,15,2026-06-04 20:03:57+00:00,2026-06-04 20:10:16+00:00,3,DIEG2026-003,Droit / Sciences politiques,Master 2 (M2),"B) Extraire le fichier, nettoyer/transformer l...",A) Les mesures et cles vers les dimensions,B) Workspace / Espace de travail > Skills,A) Administration > Reglages > Integrations,C) Administration > Fonctions > Nouvelle fonction,D) Valider et structurer les donnees recues et...,D) Generer des graphiques interactifs ou expor...,C) Stocker et exposer par API les contenus/rap...,C) Les prompts temporaires non publies,C) Afficher les rapports et declencher/recuper...,C) Des nodes connectes qui executent des actio...,"B) Lancer l'ETL, appeler les API, publier dans...",A) Piloter ou modifier des workflows et integr...,"D) Verifier l'endpoint/API appele, le slug/id ...",D) Administration > Reglages > Connexion
1,28,2026-06-05 02:35:06+00:00,2026-06-05 15:42:36+00:00,7,DIEG2026-007,Autre,Master 2 (M2),"B) Extraire le fichier, nettoyer/transformer l...",A) Les mesures et cles vers les dimensions,B) Workspace / Espace de travail > Skills,A) Administration > Reglages > Integrations,C) Administration > Fonctions > Nouvelle fonction,C) Afficher les pages React comme Next.js,D) Generer des graphiques interactifs ou expor...,A) Executer les transformations pandas,B) Les fichiers CSV bruts uniquement,C) Afficher les rapports et declencher/recuper...,C) Des nodes connectes qui executent des actio...,"B) Lancer l'ETL, appeler les API, publier dans...",A) Piloter ou modifier des workflows et integr...,"D) Verifier l'endpoint/API appele, le slug/id ...",D) Administration > Reglages > Connexion
2,63,2026-06-05 10:36:21+00:00,2026-06-05 10:44:55+00:00,9,DIEG2026-009,"EGS - Economie, Gestion & Sociologie",Master 2 (M2),"B) Extraire le fichier, nettoyer/transformer l...",A) Les mesures et cles vers les dimensions,B) Workspace / Espace de travail > Skills,A) Administration > Reglages > Integrations,C) Administration > Fonctions > Nouvelle fonction,D) Valider et structurer les donnees recues et...,D) Generer des graphiques interactifs ou expor...,C) Stocker et exposer par API les contenus/rap...,"D) Titre, contenu MDX, metriques, secteur, sta...",C) Afficher les rapports et declencher/recuper...,C) Des nodes connectes qui executent des actio...,"B) Lancer l'ETL, appeler les API, publier dans...",NaN,"D) Verifier l'endpoint/API appele, le slug/id ...",D) Administration > Reglages > Connexion

Colonnes :
['RowId', 'CreatedAt', 'UpdatedAt', 'InscriptionId', 'IDENTIFICATION', 'Filiere', "Niveau d'Etude", "Dans le TP pipeline data, un fichier CSV est depose puis un rapport doit etre disponible dans l'application. Quelle sequence de pipeline est la plus correcte ?", 'Dans un schema en etoile construit pour les rapports, que contient la table de faits ?', 'Dans Open WebUI, vous devez rendre une consigne reutilisable pour un modele. Ou cree-t-on un Skill ?', 'Dans Open WebUI, vous ajoutez un serveur MCP pour exposer des outils externes au modele. Quel espace utiliser ?', 'Dans une fonction Python Open WebUI de type Pipe ou Filter, ou ajoute-t-on le code ?', 'Dans FastAPI, pourquoi definir des schemas Pydantic pour les requetes du pipeline ?', 'Pourquoi Plotly a ete utilise dans le pipeline Python de rapport ?', 'Dans la stack pratique, quel role joue Directus ?', 'La collection session de Directus sert principalement a stocker :', "Dans Next.js, pourquoi consommer l'API Directus ou FastAPI ?", "Dans n8n, comment est structure un workflow d'automatisation ?", 'Un workflow n8n declenche par un upload doit automatiser quoi dans le TP ?', "Quel est l'interet d'Antigravity dans le contexte du TP n8n/API ?", 'Si Next.js affiche un rapport vide alors que Directus contient la session, quelle verification est prioritaire ?', 'Dans Open WebUI, pour ajouter un fournisseur LLM comme OpenAI/Ollama/OpenRouter, quelle zone est la plus adaptee ?']

# Cellule 6 — Regrouper les quatre feuilles de T1 et T2
Il est important de conserver le parcours d'origine.

In [8]:
# ============================================================
# CELLULE 6 — Regroupement des feuilles T1 et T2
# ============================================================

def detecter_parcours(nom_feuille):
    """
    Extrait DA, BI, DS ou IA depuis le nom d'une feuille.
    """

    nom = str(nom_feuille).upper()

    for parcours in ["DA", "BI", "DS", "IA"]:

        if re.search(
            rf"(^|[-_\s]){parcours}($|[-_\s])",
            nom
        ):
            return parcours

    return None


def concatener_feuilles(feuilles, etape):

    tables = []

    for nom_feuille, df in feuilles.items():

        temp = df.copy()

        temp["SOURCE_SHEET"] = nom_feuille
        temp["ETAPE"] = etape
        temp["PARCOURS"] = detecter_parcours(nom_feuille)

        tables.append(temp)

    return pd.concat(
        tables,
        ignore_index=True,
        sort=False
    )


t1 = concatener_feuilles(
    d3_sheets,
    etape="T1"
)

t2 = concatener_feuilles(
    d4_sheets,
    etape="T2"
)


print("✅ Feuilles regroupées")

print("\nT1 complet :", t1.shape)
print("T2 complet :", t2.shape)


print("\nRépartition T1 :")
display(
    t1["PARCOURS"]
    .value_counts(dropna=False)
    .rename("N")
    .to_frame()
)


print("\nRépartition T2 :")
display(
    t2["PARCOURS"]
    .value_counts(dropna=False)
    .rename("N")
    .to_frame()
)

✅ Feuilles regroupées

T1 complet : (210, 72)
T2 complet : (206, 70)

Répartition T1 :

           N
PARCOURS
BI        65
IA        62
DS        46
DA        37

Répartition T2 :

           N
PARCOURS
IA        64
BI        60
DS        48
DA        34

# Cellule 7 — Détection automatique de la colonne IDENTIFICATION

In [9]:
# ============================================================
# CELLULE 7 — Détection de l'identifiant des apprenants
# ============================================================

def normaliser_nom_colonne(texte):

    texte = str(texte)

    texte = unicodedata.normalize(
        "NFKD",
        texte
    )

    texte = "".join(
        c for c in texte
        if not unicodedata.combining(c)
    )

    texte = texte.lower().strip()

    texte = re.sub(
        r"[^a-z0-9]",
        "",
        texte
    )

    return texte


def trouver_colonne_identifiant(df):

    candidats_prioritaires = [
        "identification",
        "identifiant",
        "studentid",
        "apprenantid",
        "idapprenant",
        "userid",
        "useridentifier"
    ]

    mapping = {
        normaliser_nom_colonne(col): col
        for col in df.columns
    }

    # Recherche exacte
    for candidat in candidats_prioritaires:

        if candidat in mapping:
            return mapping[candidat]

    # Recherche approchée
    for col_norm, col_originale in mapping.items():

        if "identif" in col_norm:
            return col_originale

    return None


ID_D1 = trouver_colonne_identifiant(d1)
ID_D2 = trouver_colonne_identifiant(d2)
ID_T1 = trouver_colonne_identifiant(t1)
ID_T2 = trouver_colonne_identifiant(t2)


print("Colonnes identifiantes détectées :")

print("D1 :", ID_D1)
print("D2 :", ID_D2)
print("T1 :", ID_T1)
print("T2 :", ID_T2)

Colonnes identifiantes détectées :
D1 : IDENTIFICATION
D2 : Identification
T1 : IDENTIFICATION
T2 : IDENTIFICATION

# Cellule 8 — Normalisation technique des identifiants
On ne modifie pas encore les colonnes originales.

In [10]:
# ============================================================
# CELLULE 8 — Normalisation technique des identifiants
# ============================================================

def nettoyer_identifiant(serie):

    s = (
        serie.astype("string")
        .str.strip()
        .str.upper()
    )

    valeurs_vides = [
        "",
        "NAN",
        "NONE",
        "NULL",
        "<NA>"
    ]

    return s.replace(
        valeurs_vides,
        pd.NA
    )


for df, col_id in [
    (d1, ID_D1),
    (d2, ID_D2),
    (t1, ID_T1),
    (t2, ID_T2)
]:

    if col_id is not None:
        df["_ID_NORM"] = nettoyer_identifiant(
            df[col_id]
        )


print("✅ Identifiants normalisés dans _ID_NORM")

✅ Identifiants normalisés dans _ID_NORM

# Cellule 9 — Audit général des quatre sources

Attention : pour T1 et T2, un identifiant répété n'est pas automatiquement une erreur. Il faudra vérifier si un même apprenant apparaît dans plusieurs parcours.

In [11]:
# ============================================================
# CELLULE 9 — Audit général corrigé
# ============================================================

def resume_source(nom, df):

    if "_ID_NORM" not in df.columns:

        return {
            "Source": nom,
            "Lignes": len(df),
            "Colonnes": df.shape[1],
            "ID_non_vides": np.nan,
            "ID_uniques": np.nan,
            "ID_manquants": np.nan,
            "Lignes_avec_ID_duplique": np.nan
        }

    ids_valides = (
        df["_ID_NORM"]
        .dropna()
    )

    return {
        "Source":
            nom,

        "Lignes":
            len(df),

        "Colonnes":
            df.shape[1],

        "ID_non_vides":
            len(ids_valides),

        "ID_uniques":
            ids_valides.nunique(),

        "ID_manquants":
            df["_ID_NORM"]
            .isna()
            .sum(),

        "Lignes_avec_ID_duplique":
            ids_valides
            .duplicated(
                keep=False
            )
            .sum()
    }


audit_sources = pd.DataFrame([
    resume_source("D1 — Profil", d1),
    resume_source("D2 — T0", d2),
    resume_source("D3 — T1", t1),
    resume_source("D4 — T2", t2)
])


display(audit_sources)

        Source  Lignes  Colonnes  ID_non_vides  ID_uniques  ID_manquants  Lignes_avec_ID_duplique
0  D1 — Profil     472        20           472         472             0                        0
1      D2 — T0     315        26           305         305            10                        0
2      D3 — T1     210        73           196         196            14                        0
3      D4 — T2     206        71           206         206             0                        0

#  Cellule 10 — Valeurs manquantes

In [12]:
# ============================================================
# CELLULE 10 — Audit des valeurs manquantes
# ============================================================

def rapport_manquants(df):

    resultat = pd.DataFrame({
        "Variable": df.columns,
        "N_manquants": df.isna().sum().values,
        "Pourcentage_manquants":
            (df.isna().mean().values * 100)
    })

    return (
        resultat
        .sort_values(
            "Pourcentage_manquants",
            ascending=False
        )
        .reset_index(drop=True)
    )


for nom, df in [
    ("D1 — Profil", d1),
    ("D2 — T0", d2),
    ("D3 — T1", t1),
    ("D4 — T2", t2)
]:

    print("\n" + "=" * 80)
    print(nom)
    print("=" * 80)

    display(
        rapport_manquants(df)
        .head(20)
    )

================================================================================
D1 — Profil
================================================================================

               Variable  N_manquants  Pourcentage_manquants
0             UpdatedAt          472             100.000000
1           Source info           19               4.025424
2      Région d'origine           13               2.754237
3          Objectif pro            1               0.211864
4                 Genre            1               0.211864
5             CreatedAt            0               0.000000
6       Niveau Power BI            0               0.000000
7         Disponibilité            0               0.000000
8            Motivation            0               0.000000
9             Niveau IA            0               0.000000
10        Niveau Python            0               0.000000
11  Niveau informatique            0               0.000000
12         Niveau Excel            0               0.000000
13        Statut actuel            0               0.000000
14       Niveau d'étude            0               0.000000
15              Filière            0               0.000000
16   Année de naissance            0               0.000000
17       IDENTIFICATION            0               0.000000
18                Title            0               0.000000
19             _ID_NORM            0               0.000000

================================================================================
D2 — T0
================================================================================

                              Variable  N_manquants  Pourcentage_manquants
0                            UpdatedAt          315             100.000000
1                         Commentaires          315             100.000000
2                             _ID_NORM           10               3.174603
3                       Identification           10               3.174603
4      Q20 - Sortie fiable LLM tableau            1               0.317460
5       Q19 - Agent IA selection outil            1               0.317460
6        Q18 - Role embedding dans RAG            1               0.317460
7    Q17 - Assistant IA PDF financiers            1               0.317460
8         Q16 - Role system prompt LLM            1               0.317460
9        Q15 - Valeurs manquantes 30pc            1               0.317460
10    Q14 - Deployer modele Python API            1               0.317460
11    Q13 - Segmentation 50000 clients            1               0.317460
12      Q12 - Overfitting Underfitting            1               0.317460
13       Q11 - Bibliotheque CSV Python            1               0.317460
14  Q10 - 12 commerciaux 3 indicateurs            1               0.317460
15     Q9 - Acces directeurs regionaux            1               0.317460
16            Q8 - Vue Modele Power BI            1               0.317460
17        Q7 - CA annee precedente DAX            1               0.317460
18          Q6 - Mesure vs Colonne DAX            1               0.317460
19         Q5 - 2e grande valeur Excel            1               0.317460

================================================================================
D3 — T1
================================================================================

                                             Variable  N_manquants  Pourcentage_manquants
0                                       nc_created_by          210             100.000000
1                                       nc_updated_by          210             100.000000
2                                            nc_order          210             100.000000
3                                         nc_row_meta          210             100.000000
4                                               Title          210             100.000000
5   Dans Power Query, a quel moment doit-on typer ...          178              84.761905
6   Pourquoi le schema en etoile est-il recommande...          178              84.761905
7   Vous fusionnez (Merge) la table Ventes avec la...          178              84.761905
8   Une direction DIR (avec un espace final) dans ...          178              84.761905
9   Quelle est la propriete obligatoire d'une cle ...          178              84.761905
10  Dans un modele en etoile Power Pivot, ou se pl...          178              84.761905
11  Quel est l'ordre correct du workflow dans Powe...          178              84.761905
12  Pourquoi preferer Supprimer les autres colonne...          177              84.285714
13  Une colonne Code Postal contient la valeur 060...          177              84.285714
14  Pourquoi Power Query affiche-t-il uniquement ~...          177              84.285714
15  Quelle difference fondamentale existe entre Du...          177              84.285714
16  Dans Power Query, quelle action doit-on toujou...          177              84.285714
17  Dans le processus ETL, l'etape Transform corre...          177              84.285714
18  Parmi les 4 piliers de la qualite des donnees,...          177              84.285714
19     Qu'exprime le principe GIGO en Data Analysis ?          176              83.809524

================================================================================
D4 — T2
================================================================================

                                             Variable  N_manquants  Pourcentage_manquants
0   Vous avez [Total Montant] et une dimension Fil...          175              84.951456
1   Un taux global de presence est faible. Quelle ...          175              84.951456
2   Une table de suivi contient des cellules null ...          175              84.951456
3   Dans Power Query, une colonne Date_Commande co...          174              84.466019
4   Vous comparez Objectif et Realise par departem...          174              84.466019
5   Vous calculez Taux_Reussite = [Admis] / [Inscr...          174              84.466019
6   Dans un modele Power Pivot de facturation, que...          174              84.466019
7   Un tableau de bord Excel contient 4 TCD. Vous ...          174              84.466019
8   Avant de construire un dashboard sur les aband...          173              83.980583
9   Dans Power Query, vous devez creer une colonne...          173              83.980583
10  Une table Agences contient une ligne par agenc...          173              83.980583
11  Quelle mesure DAX compte le nombre de lignes d...          173              83.980583
12  Pour montrer l'evolution hebdomadaire du nombr...          173              83.980583
13  Vous avez une table Ventes(CodeClient, Montant...          173              83.980583
14  Vous devez stocker une categorie Age_Classe ca...          172              83.495146
15  Dans un TP churn, quel est le premier objectif...          162              78.640777
16  Une serie de ventes a une tendance visible. Po...          160              77.669903
17  Vous detectez des transactions atypiques sans ...          159              77.184466
18  Avec pandas, quelle etape permet de voir rapid...          159              77.184466
19  Pourquoi faire une selection de variables avan...          159              77.184466

# Cellule 11 — Vérification des doublons exacts

In [13]:
# ============================================================
# CELLULE 11 — Détection robuste des doublons exacts
# ============================================================

def rendre_hashable(valeur):
    """
    Convertit les objets non hashables (listes, dictionnaires, ensembles,
    tableaux NumPy...) en objets hashables afin de permettre duplicated().
    """

    if isinstance(valeur, list):
        return tuple(rendre_hashable(v) for v in valeur)

    if isinstance(valeur, tuple):
        return tuple(rendre_hashable(v) for v in valeur)

    if isinstance(valeur, dict):
        return tuple(
            sorted(
                (k, rendre_hashable(v))
                for k, v in valeur.items()
            )
        )

    if isinstance(valeur, set):
        return tuple(
            sorted(rendre_hashable(v) for v in valeur)
        )

    if isinstance(valeur, np.ndarray):
        return tuple(
            rendre_hashable(v)
            for v in valeur.tolist()
        )

    return valeur


def compter_doublons_exacts(df):
    """
    Compte les lignes entièrement dupliquées,
    même lorsque certaines colonnes contiennent des listes.
    """

    temp = df.copy()

    # On transforme seulement les colonnes susceptibles
    # de contenir des objets Python complexes
    for col in temp.select_dtypes(include=["object"]).columns:
        temp[col] = temp[col].map(rendre_hashable)

    return temp.duplicated().sum()


print("=" * 80)
print("AUDIT DES DOUBLONS EXACTS")
print("=" * 80)

for nom, df in [
    ("D1 — Profil", d1),
    ("D2 — T0", d2),
    ("D3 — T1", t1),
    ("D4 — T2", t2)
]:

    doublons_exacts = compter_doublons_exacts(df)

    print(
        f"{nom:15s} : "
        f"{doublons_exacts} doublon(s) exact(s)"
    )

================================================================================
AUDIT DES DOUBLONS EXACTS
================================================================================
D1 — Profil     : 0 doublon(s) exact(s)
D2 — T0         : 0 doublon(s) exact(s)
D3 — T1         : 0 doublon(s) exact(s)
D4 — T2         : 0 doublon(s) exact(s)

In [14]:
# ============================================================
# CELLULE 11B — Identifiants apparaissant plusieurs fois
# ============================================================

for nom, df in [
    ("D1 — Profil", d1),
    ("D2 — T0", d2),
    ("D3 — T1", t1),
    ("D4 — T2", t2)
]:

    print("\n" + "=" * 80)
    print(nom)
    print("=" * 80)

    if "_ID_NORM" not in df.columns:
        print("❌ Aucun identifiant détecté")
        continue

    counts = (
        df["_ID_NORM"]
        .dropna()
        .value_counts()
    )

    ids_repetes = counts[counts > 1]

    print(
        "Nombre d'identifiants apparaissant plusieurs fois :",
        len(ids_repetes)
    )

    if len(ids_repetes) > 0:
        display(
            ids_repetes
            .head(30)
            .rename("Nombre_occurrences")
            .to_frame()
        )
    else:
        print("✅ Aucun identifiant répété")

================================================================================
D1 — Profil
================================================================================
Nombre d'identifiants apparaissant plusieurs fois : 0
✅ Aucun identifiant répété

================================================================================
D2 — T0
================================================================================
Nombre d'identifiants apparaissant plusieurs fois : 0
✅ Aucun identifiant répété

================================================================================
D3 — T1
================================================================================
Nombre d'identifiants apparaissant plusieurs fois : 0
✅ Aucun identifiant répété

================================================================================
D4 — T2
================================================================================
Nombre d'identifiants apparaissant plusieurs fois : 0
✅ Aucun identifiant répété

In [15]:
for nom, df in [
    ("D1 — Profil", d1),
    ("D2 — T0", d2),
    ("D3 — T1", t1),
    ("D4 — T2", t2)
]:

    print("\n" + "=" * 80)
    print(nom)
    print("=" * 80)

    if "_ID_NORM" not in df.columns:
        print("❌ Aucun identifiant détecté")
        continue

    counts = (
        df["_ID_NORM"]
        .value_counts(dropna=True)
    )

    display(
        counts[counts > 1]
        .head(30)
        .rename("Nombre_occurrences")
        .to_frame()
    )

================================================================================
D1 — Profil
================================================================================

Empty DataFrame
Columns: [Nombre_occurrences]
Index: []

================================================================================
D2 — T0
================================================================================

Empty DataFrame
Columns: [Nombre_occurrences]
Index: []

================================================================================
D3 — T1
================================================================================

Empty DataFrame
Columns: [Nombre_occurrences]
Index: []

================================================================================
D4 — T2
================================================================================

Empty DataFrame
Columns: [Nombre_occurrences]
Index: []

# Cellule 12 — Cohortes communes D1 / T0 / T1 / T2

cellule important

In [16]:
# ============================================================
# CELLULE 12 — Correspondance longitudinale des apprenants
# ============================================================

def ensemble_ids(df):

    if "_ID_NORM" not in df.columns:
        return set()

    return set(
        df["_ID_NORM"]
        .dropna()
        .unique()
    )


IDS_D1 = ensemble_ids(d1)
IDS_T0 = ensemble_ids(d2)
IDS_T1 = ensemble_ids(t1)
IDS_T2 = ensemble_ids(t2)


print("Nombre d'apprenants uniques")
print("--------------------------------")
print("D1 :", len(IDS_D1))
print("T0 :", len(IDS_T0))
print("T1 :", len(IDS_T1))
print("T2 :", len(IDS_T2))

Nombre d'apprenants uniques
--------------------------------
D1 : 472
T0 : 305
T1 : 196
T2 : 206

M_T0 = Profil + T0 → T2

M_T1 = Profil + T0 + T1 → T2

In [17]:
# Cohortes principales

COHORTE_D1_T0 = (
    IDS_D1
    & IDS_T0
)

COHORTE_MT0 = (
    IDS_D1
    & IDS_T0
    & IDS_T2
)

COHORTE_MT1 = (
    IDS_D1
    & IDS_T0
    & IDS_T1
    & IDS_T2
)


audit_cohortes = pd.DataFrame({

    "Cohorte": [
        "D1",
        "T0",
        "T1",
        "T2",
        "D1 ∩ T0",
        "M_T0 : D1 ∩ T0 ∩ T2",
        "M_T1 : D1 ∩ T0 ∩ T1 ∩ T2"
    ],

    "N_apprenants": [
        len(IDS_D1),
        len(IDS_T0),
        len(IDS_T1),
        len(IDS_T2),
        len(COHORTE_D1_T0),
        len(COHORTE_MT0),
        len(COHORTE_MT1)
    ]

})


display(audit_cohortes)

                    Cohorte  N_apprenants
0                        D1           472
1                        T0           305
2                        T1           196
3                        T2           206
4                   D1 ∩ T0           305
5       M_T0 : D1 ∩ T0 ∩ T2           128
6  M_T1 : D1 ∩ T0 ∩ T1 ∩ T2           125

# Cellule 13 — Matrice des correspondances entre sources

La diagonale donne le nombre d'identifiants uniques de chaque source.
Les autres cases indiquent le nombre d'apprenants retrouvés dans les deux sources.

In [18]:
# ============================================================
# CELLULE 13 — Matrice des correspondances d'identifiants
# ============================================================

sources_ids = {
    "D1": IDS_D1,
    "T0": IDS_T0,
    "T1": IDS_T1,
    "T2": IDS_T2
}


matrice = pd.DataFrame(
    index=sources_ids.keys(),
    columns=sources_ids.keys(),
    dtype=int
)


for source_a, ids_a in sources_ids.items():

    for source_b, ids_b in sources_ids.items():

        matrice.loc[
            source_a,
            source_b
        ] = len(
            ids_a & ids_b
        )


display(matrice)

       D1     T0     T1     T2
D1  472.0  305.0  141.0  146.0
T0  305.0  305.0  125.0  128.0
T1  141.0  125.0  196.0  196.0
T2  146.0  128.0  196.0  206.0

# Cellule 14 — Identifiants absents entre les étapes

In [19]:
# ============================================================
# CELLULE 14 — Analyse de l'attrition / identifiants absents
# ============================================================

print("Présents dans D1 mais absents de T0 :")
print(
    len(
        IDS_D1 - IDS_T0
    )
)


print("\nPrésents dans T0 mais absents de T1 :")
print(
    len(
        IDS_T0 - IDS_T1
    )
)


print("\nPrésents dans T1 mais absents de T2 :")
print(
    len(
        IDS_T1 - IDS_T2
    )
)


print("\nPrésents dans T0 mais absents de T2 :")
print(
    len(
        IDS_T0 - IDS_T2
    )
)

Présents dans D1 mais absents de T0 :
167

Présents dans T0 mais absents de T1 :
180

Présents dans T1 mais absents de T2 :
0

Présents dans T0 mais absents de T2 :
177

# Puis affichage de quelques identifiants :

In [20]:
print("\nExemples D1 sans T0 :")
print(
    sorted(
        list(IDS_D1 - IDS_T0)
    )[:20]
)


print("\nExemples T0 sans T1 :")
print(
    sorted(
        list(IDS_T0 - IDS_T1)
    )[:20]
)


print("\nExemples T1 sans T2 :")
print(
    sorted(
        list(IDS_T1 - IDS_T2)
    )[:20]
)

Exemples D1 sans T0 :
['DIEG2026-010', 'DIEG2026-020', 'DIEG2026-021', 'DIEG2026-022', 'DIEG2026-023', 'DIEG2026-044', 'DIEG2026-059', 'DIEG2026-062', 'DIEG2026-066', 'DIEG2026-067', 'DIEG2026-071', 'DIEG2026-072', 'DIEG2026-075', 'DIEG2026-082', 'DIEG2026-083', 'DIEG2026-086', 'DIEG2026-089', 'DIEG2026-092', 'DIEG2026-095', 'DIEG2026-100']

Exemples T0 sans T1 :
['DIEG2026-001', 'DIEG2026-002', 'DIEG2026-004', 'DIEG2026-005', 'DIEG2026-006', 'DIEG2026-011', 'DIEG2026-013', 'DIEG2026-014', 'DIEG2026-015', 'DIEG2026-016', 'DIEG2026-017', 'DIEG2026-018', 'DIEG2026-019', 'DIEG2026-024', 'DIEG2026-031', 'DIEG2026-033', 'DIEG2026-039', 'DIEG2026-046', 'DIEG2026-049', 'DIEG2026-050']

Exemples T1 sans T2 :
[]

# Cellule 15 — Vérification des parcours T1 et T2

In [21]:
# ============================================================
# CELLULE 15 — Cohérence des parcours T1 / T2
# ============================================================

print("T1 — effectifs par parcours")

display(
    t1.groupby("PARCOURS")
    .agg(
        Lignes=("_ID_NORM", "size"),
        Apprenants_uniques=("_ID_NORM", "nunique")
    )
)


print("\nT2 — effectifs par parcours")

display(
    t2.groupby("PARCOURS")
    .agg(
        Lignes=("_ID_NORM", "size"),
        Apprenants_uniques=("_ID_NORM", "nunique")
    )
)

T1 — effectifs par parcours

          Lignes  Apprenants_uniques
PARCOURS
BI            65                  60
DA            37                  32
DS            46                  44
IA            62                  60

T2 — effectifs par parcours

          Lignes  Apprenants_uniques
PARCOURS
BI            60                  60
DA            34                  34
DS            48                  48
IA            64                  64

# Puis :

In [22]:
# Nombre de parcours T1 par apprenant

nb_parcours_t1 = (
    t1.dropna(
        subset=["_ID_NORM"]
    )
    .groupby("_ID_NORM")["PARCOURS"]
    .nunique()
)


print(
    "Apprenants présents dans plusieurs parcours à T1 :",
    (nb_parcours_t1 > 1).sum()
)


# Nombre de parcours T2 par apprenant

nb_parcours_t2 = (
    t2.dropna(
        subset=["_ID_NORM"]
    )
    .groupby("_ID_NORM")["PARCOURS"]
    .nunique()
)


print(
    "Apprenants présents dans plusieurs parcours à T2 :",
    (nb_parcours_t2 > 1).sum()
)

Apprenants présents dans plusieurs parcours à T1 : 0
Apprenants présents dans plusieurs parcours à T2 : 0

# Cellule 16 — Sauvegarder les résultats de l'audit

In [23]:
# ============================================================
# CELLULE 16 — Exports de l'audit
# ============================================================

audit_sources.to_csv(
    OUTPUT_DIR / "audit_sources.csv",
    index=False,
    encoding="utf-8-sig"
)

audit_cohortes.to_csv(
    OUTPUT_DIR / "audit_cohortes.csv",
    index=False,
    encoding="utf-8-sig"
)

matrice.to_csv(
    OUTPUT_DIR / "audit_correspondances_ids.csv",
    encoding="utf-8-sig"
)

rapport_manquants(d1).to_csv(
    OUTPUT_DIR / "audit_manquants_D1.csv",
    index=False,
    encoding="utf-8-sig"
)

rapport_manquants(d2).to_csv(
    OUTPUT_DIR / "audit_manquants_T0.csv",
    index=False,
    encoding="utf-8-sig"
)

rapport_manquants(t1).to_csv(
    OUTPUT_DIR / "audit_manquants_T1.csv",
    index=False,
    encoding="utf-8-sig"
)

rapport_manquants(t2).to_csv(
    OUTPUT_DIR / "audit_manquants_T2.csv",
    index=False,
    encoding="utf-8-sig"
)


print("✅ Audit sauvegardé dans :")
print(OUTPUT_DIR.resolve())

✅ Audit sauvegardé dans :
/home/andrycomputer/Documents/Model-eval-pers-elearning/outputs/00_audit

# Cellule 17

In [24]:
# ============================================================
# CELLULE 17 — Analyse des identifiants non appariés
# ============================================================

print("=" * 80)
print("IDENTIFIANTS NON APPARIÉS")
print("=" * 80)

t1_sans_d1 = sorted(IDS_T1 - IDS_D1)
t2_sans_d1 = sorted(IDS_T2 - IDS_D1)

d1_sans_t1 = sorted(IDS_D1 - IDS_T1)
d1_sans_t2 = sorted(IDS_D1 - IDS_T2)

print("\nT1 présents mais absents de D1 :", len(t1_sans_d1))
print(t1_sans_d1[:50])

print("\nT2 présents mais absents de D1 :", len(t2_sans_d1))
print(t2_sans_d1[:50])

print("\nD1 présents mais absents de T1 :", len(d1_sans_t1))
print(d1_sans_t1[:50])

print("\nD1 présents mais absents de T2 :", len(d1_sans_t2))
print(d1_sans_t2[:50])

================================================================================
IDENTIFIANTS NON APPARIÉS
================================================================================

T1 présents mais absents de D1 : 55
['DIEG2026-477', 'DIEG2026-481', 'DIEG2026-497', 'DIEG2026-498', 'DIEG2026-509', 'DIEG2026-512', 'DIEG2026-519', 'DIEG2026-520', 'DIEG2026-524', 'DIEG2026-526', 'DIEG2026-528', 'DIEG2026-532', 'DIEG2026-535', 'DIEG2026-537', 'DIEG2026-541', 'DIEG2026-546', 'DIEG2026-550', 'DIEG2026-551', 'DIEG2026-554', 'DIEG2026-555', 'DIEG2026-557', 'DIEG2026-558', 'DIEG2026-560', 'DIEG2026-564', 'DIEG2026-571', 'DIEG2026-574', 'DIEG2026-576', 'DIEG2026-579', 'DIEG2026-584', 'DIEG2026-589', 'DIEG2026-597', 'DIEG2026-598', 'DIEG2026-600', 'DIEG2026-601', 'DIEG2026-604', 'DIEG2026-609', 'DIEG2026-610', 'DIEG2026-611', 'DIEG2026-614', 'DIEG2026-615', 'DIEG2026-616', 'DIEG2026-617', 'DIEG2026-623', 'DIEG2026-625', 'DIEG2026-626', 'DIEG2026-627', 'DIEG2026-630', 'DIEG2026-631', 'DIEG2026-633', 'DIEG2026-636']

T2 présents mais absents de D1 : 60
['DIEG2026-473', 'DIEG2026-477', 'DIEG2026-481', 'DIEG2026-497', 'DIEG2026-498', 'DIEG2026-509', 'DIEG2026-511', 'DIEG2026-512', 'DIEG2026-519', 'DIEG2026-520', 'DIEG2026-524', 'DIEG2026-526', 'DIEG2026-528', 'DIEG2026-532', 'DIEG2026-535', 'DIEG2026-537', 'DIEG2026-541', 'DIEG2026-546', 'DIEG2026-550', 'DIEG2026-551', 'DIEG2026-554', 'DIEG2026-555', 'DIEG2026-557', 'DIEG2026-558', 'DIEG2026-560', 'DIEG2026-563', 'DIEG2026-564', 'DIEG2026-571', 'DIEG2026-572', 'DIEG2026-574', 'DIEG2026-576', 'DIEG2026-579', 'DIEG2026-584', 'DIEG2026-589', 'DIEG2026-596', 'DIEG2026-597', 'DIEG2026-598', 'DIEG2026-600', 'DIEG2026-601', 'DIEG2026-604', 'DIEG2026-609', 'DIEG2026-610', 'DIEG2026-611', 'DIEG2026-614', 'DIEG2026-615', 'DIEG2026-616', 'DIEG2026-617', 'DIEG2026-623', 'DIEG2026-625', 'DIEG2026-626']

D1 présents mais absents de T1 : 331
['DIEG2026-001', 'DIEG2026-002', 'DIEG2026-004', 'DIEG2026-005', 'DIEG2026-006', 'DIEG2026-011', 'DIEG2026-013', 'DIEG2026-014', 'DIEG2026-015', 'DIEG2026-016', 'DIEG2026-017', 'DIEG2026-018', 'DIEG2026-019', 'DIEG2026-020', 'DIEG2026-021', 'DIEG2026-023', 'DIEG2026-024', 'DIEG2026-031', 'DIEG2026-033', 'DIEG2026-039', 'DIEG2026-046', 'DIEG2026-049', 'DIEG2026-050', 'DIEG2026-058', 'DIEG2026-059', 'DIEG2026-060', 'DIEG2026-062', 'DIEG2026-063', 'DIEG2026-064', 'DIEG2026-066', 'DIEG2026-068', 'DIEG2026-071', 'DIEG2026-074', 'DIEG2026-075', 'DIEG2026-078', 'DIEG2026-079', 'DIEG2026-080', 'DIEG2026-081', 'DIEG2026-082', 'DIEG2026-083', 'DIEG2026-086', 'DIEG2026-088', 'DIEG2026-089', 'DIEG2026-090', 'DIEG2026-091', 'DIEG2026-093', 'DIEG2026-095', 'DIEG2026-096', 'DIEG2026-097', 'DIEG2026-100']

D1 présents mais absents de T2 : 326
['DIEG2026-001', 'DIEG2026-002', 'DIEG2026-004', 'DIEG2026-005', 'DIEG2026-006', 'DIEG2026-011', 'DIEG2026-013', 'DIEG2026-014', 'DIEG2026-015', 'DIEG2026-016', 'DIEG2026-017', 'DIEG2026-018', 'DIEG2026-019', 'DIEG2026-020', 'DIEG2026-021', 'DIEG2026-023', 'DIEG2026-024', 'DIEG2026-031', 'DIEG2026-033', 'DIEG2026-039', 'DIEG2026-046', 'DIEG2026-049', 'DIEG2026-050', 'DIEG2026-058', 'DIEG2026-059', 'DIEG2026-060', 'DIEG2026-062', 'DIEG2026-063', 'DIEG2026-064', 'DIEG2026-066', 'DIEG2026-068', 'DIEG2026-071', 'DIEG2026-074', 'DIEG2026-075', 'DIEG2026-078', 'DIEG2026-079', 'DIEG2026-080', 'DIEG2026-081', 'DIEG2026-082', 'DIEG2026-083', 'DIEG2026-086', 'DIEG2026-088', 'DIEG2026-089', 'DIEG2026-090', 'DIEG2026-091', 'DIEG2026-093', 'DIEG2026-095', 'DIEG2026-096', 'DIEG2026-097', 'DIEG2026-100']

# T1 est entièrement inclus dans T2

In [25]:
# Vérifier si les mêmes IDs problématiques apparaissent à la fois dans T1 et T2

problemes_communs_t1_t2 = (
    (IDS_T1 - IDS_D1)
    & (IDS_T2 - IDS_D1)
)

print(
    "IDs présents dans T1 et T2 mais absents de D1 :",
    len(problemes_communs_t1_t2)
)

print(sorted(problemes_communs_t1_t2)[:100])

IDs présents dans T1 et T2 mais absents de D1 : 55
['DIEG2026-477', 'DIEG2026-481', 'DIEG2026-497', 'DIEG2026-498', 'DIEG2026-509', 'DIEG2026-512', 'DIEG2026-519', 'DIEG2026-520', 'DIEG2026-524', 'DIEG2026-526', 'DIEG2026-528', 'DIEG2026-532', 'DIEG2026-535', 'DIEG2026-537', 'DIEG2026-541', 'DIEG2026-546', 'DIEG2026-550', 'DIEG2026-551', 'DIEG2026-554', 'DIEG2026-555', 'DIEG2026-557', 'DIEG2026-558', 'DIEG2026-560', 'DIEG2026-564', 'DIEG2026-571', 'DIEG2026-574', 'DIEG2026-576', 'DIEG2026-579', 'DIEG2026-584', 'DIEG2026-589', 'DIEG2026-597', 'DIEG2026-598', 'DIEG2026-600', 'DIEG2026-601', 'DIEG2026-604', 'DIEG2026-609', 'DIEG2026-610', 'DIEG2026-611', 'DIEG2026-614', 'DIEG2026-615', 'DIEG2026-616', 'DIEG2026-617', 'DIEG2026-623', 'DIEG2026-625', 'DIEG2026-626', 'DIEG2026-627', 'DIEG2026-630', 'DIEG2026-631', 'DIEG2026-633', 'DIEG2026-636', 'DIEG2026-637', 'DIEG2026-639', 'DIEG2026-643', 'DIEG2026-654', 'DIEG2026-656']

In [26]:
# ============================================================
# CELLULE 18 — Lignes T0 sans identifiant
# ============================================================

t0_sans_id = d2[d2["_ID_NORM"].isna()].copy()

print("Nombre de lignes T0 sans ID :", len(t0_sans_id))

display(t0_sans_id)

Nombre de lignes T0 sans ID : 10

,CreatedAt,UpdatedAt,Date du test,Q1 - Resume ventes Excel,Q2 - Import CSV Excel,Q3 - Modele donnees Excel,Q4 - Mauvaise pratique visu Excel,Q5 - 2e grande valeur Excel,Q6 - Mesure vs Colonne DAX,Q7 - CA annee precedente DAX,Q8 - Vue Modele Power BI,Q9 - Acces directeurs regionaux,Q10 - 12 commerciaux 3 indicateurs,Q11 - Bibliotheque CSV Python,Q12 - Overfitting Underfitting,Q13 - Segmentation 50000 clients,Q14 - Deployer modele Python API,Q15 - Valeurs manquantes 30pc,Q16 - Role system prompt LLM,Q17 - Assistant IA PDF financiers,Q18 - Role embedding dans RAG,Q19 - Agent IA selection outil,Q20 - Sortie fiable LLM tableau,Commentaires,Identification,_ID_NORM
0,2026-03-31 17:09:03+00:00,None,2026-03-31 17:09:02+00:00,B. Tableau croise dynamique (TCD),D. Power Query,C. Power Pivot avec relations,A. Courbes pour tendances temporelles,D. RANG(plage;2),D. Mesure ne peut pas utiliser DAX,B. CALCULATE(SUM SAMEPERIODLASTYEAR),C. Ecrire requetes Power Query,E. Je ne sais pas,A. Histogramme empile,B. scikit-learn,B. Erreur matrice de confusion,A. Reseau de neurones recurrent,C. FastAPI ou Flask + joblib ou pickle,B. Remplacer par 0,D. Definir role et contraintes du modele,B. RAG - indexer et recuperer dynamiquement,B. Authentifier utilisateur,B. Ordre dans lequel les outils sont listes,D. JSON structure avec schema defini,None,None,<NA>
1,2026-03-31 17:41:49+00:00,None,2026-03-31 17:41:48+00:00,C. Formule SOMME(),B. Copier-coller manuellement,D. Formules RECHERCHEV,D. Graphique 3D explose,B. GRANDE.VALEUR(plage;2),C. Mesure=visualisation Colonne=stockee,B. CALCULATE(SUM SAMEPERIODLASTYEAR),D. Definir relations entre tables,A. Filtrer manuellement les visuels,D. Radar ou tableau matriciel conditionnel,C. pandas,A. Probleme de normalisation,B. K-Means Clustering,C. FastAPI ou Flask + joblib ou pickle,B. Remplacer par 0,A. Connecter a une base de donnees,D. Connaissances integrees du LLM uniquement,D. Transformer texte en vecteurs numeriques,A. Vote aleatoire,C. Augmenter la temperature,None,None,<NA>
2,2026-03-31 18:19:08+00:00,None,2026-03-31 18:19:07+00:00,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,None,None,<NA>
3,2026-03-31 18:25:08+00:00,None,2026-03-31 18:25:06+00:00,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,None,None,<NA>
4,2026-03-31 20:12:55+00:00,None,2026-03-31 20:12:54+00:00,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,None,None,<NA>
5,2026-03-31 20:43:51+00:00,None,2026-03-31 20:43:50+00:00,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,None,None,<NA>
6,2026-03-31 20:51:13+00:00,None,2026-03-31 20:51:13+00:00,B. Tableau croise dynamique (TCD),C. Formules SI imbriquees,D. Formules RECHERCHEV,D. Graphique 3D explose,E. Je ne sais pas,E. Je ne sais pas,B. CALCULATE(SUM SAMEPERIODLASTYEAR),B. Publier sur Power BI Service,A. Filtrer manuellement les visuels,D. Radar ou tableau matriciel conditionnel,D. numpy,B. Erreur matrice de confusion,A. Reseau de neurones recurrent,C. FastAPI ou Flask + joblib ou pickle,D. Supprimer toutes les lignes,A. Connecter a une base de donnees,E. Je ne sais pas,A. Generer la reponse finale,E. Je ne sais pas,A. Reduire longueur du prompt,None,None,<NA>
7,2026-03-31 22:16:12+00:00,None,2026-03-31 22:16:11+00:00,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,None,None,<NA>
18,2026-04-01 08:18:18+00:00,None,2026-04-01 08:18:15+00:00,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,E. Je ne sais pas,None,None,<NA>
222,2026-04-21 13:16:05+00:00,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>

In [27]:
# ============================================================
# CELLULE 19 — Analyse détaillée des IDs répétés à T1
# ============================================================

counts_t1 = (
    t1["_ID_NORM"]
    .dropna()
    .value_counts()
)

ids_t1_repetes = counts_t1[counts_t1 > 1].index

t1_repetes = (
    t1[t1["_ID_NORM"].isin(ids_t1_repetes)]
    .sort_values(["_ID_NORM", "PARCOURS"])
)

print(
    "Nombre d'apprenants ayant plusieurs lignes à T1 :",
    len(ids_t1_repetes)
)

display(
    t1_repetes[
        ["_ID_NORM", "PARCOURS", "SOURCE_SHEET"]
    ]
)

Nombre d'apprenants ayant plusieurs lignes à T1 : 0

Empty DataFrame
Columns: [_ID_NORM, PARCOURS, SOURCE_SHEET]
Index: []

In [28]:
# ============================================================
# CELLULE 20 — Classification des lignes T0 sans identifiant
# ============================================================

t0_sans_id = d2[d2["_ID_NORM"].isna()].copy()

# Colonnes des 20 questions
question_cols_t0 = [
    col for col in d2.columns
    if re.match(r"^Q\d+\s*-", str(col))
]

print("Nombre de colonnes de questions détectées :", len(question_cols_t0))


# Nombre de réponses réellement présentes
t0_sans_id["NB_REPONSES"] = (
    t0_sans_id[question_cols_t0]
    .notna()
    .sum(axis=1)
)


display(
    t0_sans_id[
        [
            "CreatedAt",
            "Date du test",
            "Identification",
            "NB_REPONSES"
        ]
    ]
)


print(
    "\nLignes sans ID mais contenant des réponses :",
    (t0_sans_id["NB_REPONSES"] > 0).sum()
)

print(
    "Lignes sans ID et sans aucune réponse :",
    (t0_sans_id["NB_REPONSES"] == 0).sum()
)

Nombre de colonnes de questions détectées : 20

                     CreatedAt               Date du test Identification  NB_REPONSES
0    2026-03-31 17:09:03+00:00  2026-03-31 17:09:02+00:00           None           20
1    2026-03-31 17:41:49+00:00  2026-03-31 17:41:48+00:00           None           20
2    2026-03-31 18:19:08+00:00  2026-03-31 18:19:07+00:00           None           20
3    2026-03-31 18:25:08+00:00  2026-03-31 18:25:06+00:00           None           20
4    2026-03-31 20:12:55+00:00  2026-03-31 20:12:54+00:00           None           20
5    2026-03-31 20:43:51+00:00  2026-03-31 20:43:50+00:00           None           20
6    2026-03-31 20:51:13+00:00  2026-03-31 20:51:13+00:00           None           20
7    2026-03-31 22:16:12+00:00  2026-03-31 22:16:11+00:00           None           20
18   2026-04-01 08:18:18+00:00  2026-04-01 08:18:15+00:00           None           20
222  2026-04-21 13:16:05+00:00                       None           None            0

Lignes sans ID mais contenant des réponses : 9
Lignes sans ID et sans aucune réponse : 1

# Vérifions maintenant l'hypothèse du fichier D1 trop ancien

In [29]:
# ============================================================
# CELLULE 21 — Analyse numérique des identifiants
# ============================================================

def numero_id(id_value):
    if pd.isna(id_value):
        return np.nan

    match = re.search(r"(\d+)$", str(id_value))

    if match:
        return int(match.group(1))

    return np.nan


resume_ids = []

for nom, df in [
    ("D1", d1),
    ("T0", d2),
    ("T1", t1),
    ("T2", t2)
]:

    numeros = (
        df["_ID_NORM"]
        .dropna()
        .map(numero_id)
        .dropna()
    )

    resume_ids.append({
        "Source": nom,
        "N_ID": df["_ID_NORM"].notna().sum(),
        "N_uniques": df["_ID_NORM"].nunique(),
        "ID_min": int(numeros.min()) if len(numeros) else None,
        "ID_max": int(numeros.max()) if len(numeros) else None
    })


resume_ids = pd.DataFrame(resume_ids)

display(resume_ids)

  Source  N_ID  N_uniques  ID_min  ID_max
0     D1   472        472       1     472
1     T0   305        305       1     471
2     T1   196        196       3     656
3     T2   206        206       3     656

# Vérifier aussi les 14 lignes T1 sans identifiant

In [30]:
# ============================================================
# CELLULE 22 — Analyse des lignes T1 sans identifiant
# ============================================================

t1_sans_id = t1[t1["_ID_NORM"].isna()].copy()

print("Nombre de lignes T1 sans identifiant :", len(t1_sans_id))

display(
    t1_sans_id[
        [
            col for col in [
                "SOURCE_SHEET",
                "PARCOURS",
                ID_T1
            ]
            if col in t1_sans_id.columns
        ]
    ]
)

Nombre de lignes T1 sans identifiant : 14

    SOURCE_SHEET PARCOURS IDENTIFICATION
0     MI-TEST-DA       DA            NaN
3     MI-TEST-DA       DA            NaN
6     MI-TEST-DA       DA            NaN
11    MI-TEST-DA       DA            NaN
31    MI-TEST-DA       DA            NaN
37    MI-TEST-BI       BI            NaN
38    MI-TEST-BI       BI            NaN
39    MI-TEST-BI       BI            NaN
82    MI-TEST-BI       BI            NaN
95    MI-TEST-BI       BI            NaN
104   MI-TEST-DS       DS            NaN
113   MI-TEST-DS       DS            NaN
167   MI-TEST-IA       IA            NaN
197   MI-TEST-IA       IA            NaN

# Puis nous devons savoir si ce sont de vraies réponses :

In [31]:
# Nombre de valeurs renseignées sur chaque ligne T1 sans ID

colonnes_utiles_t1 = [
    col for col in t1.columns
    if col not in [
        "_ID_NORM",
        "SOURCE_SHEET",
        "ETAPE",
        "PARCOURS"
    ]
]

t1_sans_id["NB_VALEURS_RENSEIGNEES"] = (
    t1_sans_id[colonnes_utiles_t1]
    .notna()
    .sum(axis=1)
)

display(
    t1_sans_id[
        [
            "SOURCE_SHEET",
            "PARCOURS",
            "NB_VALEURS_RENSEIGNEES"
        ]
    ]
)

    SOURCE_SHEET PARCOURS  NB_VALEURS_RENSEIGNEES
0     MI-TEST-DA       DA                      11
3     MI-TEST-DA       DA                       3
6     MI-TEST-DA       DA                       3
11    MI-TEST-DA       DA                       4
31    MI-TEST-DA       DA                       3
37    MI-TEST-BI       BI                       3
38    MI-TEST-BI       BI                      18
39    MI-TEST-BI       BI                      18
82    MI-TEST-BI       BI                       3
95    MI-TEST-BI       BI                       3
104   MI-TEST-DS       DS                       3
113   MI-TEST-DS       DS                       4
167   MI-TEST-IA       IA                       4
197   MI-TEST-IA       IA                       4

# Cellule 23 — Compter précisément les réponses T1

Vous devriez voir clairement trois catégories :
- lignes sans aucune réponse ;
- tests abandonnés après une ou quelques questions ;
- véritables tests remplis mais sans identification.

In [32]:
# ============================================================
# CELLULE 23 — Complétude T1 correctement calculée par feuille
# ============================================================

META_COLS_T1 = {
    "identification",
    "id",
    "rowid",
    "createdat",
    "updatedat",
    "nccreatedby",
    "ncupdatedby",
    "ncorder",
    "ncrowmeta",
    "title",
    "inscriptionid",
    "filiere",
    "niveaudetude"
}


def est_metadata_t1(col):

    return (
        normaliser_nom_colonne(col)
        in META_COLS_T1
    )


resultats_completude_t1 = []


for feuille, df in d3_sheets.items():

    parcours = detecter_parcours(
        feuille
    )

    id_col = trouver_colonne_identifiant(
        df
    )

    q_cols = [
        col
        for col in df.columns
        if not est_metadata_t1(col)
    ]

    print(
        feuille,
        parcours,
        "questions =",
        len(q_cols)
    )

    # T1 doit comporter 15 questions par parcours
    assert len(q_cols) == 15, (
        f"{feuille} : {len(q_cols)} questions détectées"
    )

    ids = nettoyer_identifiant(
        df[id_col]
    )

    temp = pd.DataFrame({
        "_ID_NORM":
            ids,

        "SOURCE_SHEET":
            feuille,

        "PARCOURS":
            parcours,

        "NB_QUESTIONS_T1":
            len(q_cols),

        "NB_REPONSES_T1":
            df[q_cols]
            .notna()
            .sum(axis=1)
    })

    temp["TAUX_COMPLETUDE_T1"] = (
        temp["NB_REPONSES_T1"]
        /
        temp["NB_QUESTIONS_T1"]
        * 100
    )

    resultats_completude_t1.append(
        temp
    )


t1_completude = pd.concat(
    resultats_completude_t1,
    ignore_index=True
)


display(
    t1_completude[
        t1_completude[
            "_ID_NORM"
        ].isna()
    ]
)


assert (
    t1_completude[
        "NB_QUESTIONS_T1"
    ] == 15
).all()


print(
    "✅ Complétude T1 calculée sur 15 questions par parcours"
)

MI-TEST-DA DA questions = 15
MI-TEST-BI BI questions = 15

MI-TEST-DS DS questions = 15
MI-TEST-IA IA questions = 15

    _ID_NORM SOURCE_SHEET PARCOURS  NB_QUESTIONS_T1  NB_REPONSES_T1  TAUX_COMPLETUDE_T1
0       <NA>   MI-TEST-DA       DA               15               8           53.333333
3       <NA>   MI-TEST-DA       DA               15               0            0.000000
6       <NA>   MI-TEST-DA       DA               15               0            0.000000
11      <NA>   MI-TEST-DA       DA               15               1            6.666667
31      <NA>   MI-TEST-DA       DA               15               0            0.000000
37      <NA>   MI-TEST-BI       BI               15               0            0.000000
38      <NA>   MI-TEST-BI       BI               15              15          100.000000
39      <NA>   MI-TEST-BI       BI               15              15          100.000000
82      <NA>   MI-TEST-BI       BI               15               0            0.000000
95      <NA>   MI-TEST-BI       BI               15               0            0.000000
104     <NA>   MI-TEST-DS       DS               15               0            0.000000
113     <NA>   MI-TEST-DS       DS               15               1            6.666667
167     <NA>   MI-TEST-IA       IA               15               1            6.666667
197     <NA>   MI-TEST-IA       IA               15               1            6.666667

✅ Complétude T1 calculée sur 15 questions par parcours

# Cellule 24 — Séparer données exploitables et données non appariables

In [33]:
# ============================================================
# CELLULE 24 — Séparation des données analytiques
# ============================================================

# -----------------------------
# T0
# -----------------------------

t0_analytique = d2[
    d2["_ID_NORM"].notna()
].copy()

t0_sans_identifiant = d2[
    d2["_ID_NORM"].isna()
].copy()


# -----------------------------
# T1
# -----------------------------

t1_analytique = t1[
    t1["_ID_NORM"].notna()
].copy()

t1_sans_identifiant = t1[
    t1["_ID_NORM"].isna()
].copy()


# -----------------------------
# D1
# -----------------------------

d1_analytique = d1[
    d1["_ID_NORM"].notna()
].copy()


# -----------------------------
# T2
# -----------------------------

t2_analytique = t2[
    t2["_ID_NORM"].notna()
].copy()


print("D1 analytique :", d1_analytique.shape)
print("T0 analytique :", t0_analytique.shape)
print("T1 analytique :", t1_analytique.shape)
print("T2 analytique :", t2_analytique.shape)

print("\nSoumissions conservées à part :")
print("T0 sans ID :", len(t0_sans_identifiant))
print("T1 sans ID :", len(t1_sans_identifiant))

D1 analytique : (472, 20)
T0 analytique : (305, 26)
T1 analytique : (196, 73)
T2 analytique : (206, 71)

Soumissions conservées à part :
T0 sans ID : 10
T1 sans ID : 14

# Cellule 25 — Vérifier que les IDs analytiques sont uniques

In [34]:
# ============================================================
# CELLULE 25 — Unicité des identifiants
# ============================================================

def audit_unicite(nom, df):

    n = len(df)

    n_ids = df["_ID_NORM"].nunique()

    n_dupliques = (
        df["_ID_NORM"]
        .duplicated(keep=False)
        .sum()
    )

    print(
        f"{nom:15s} | "
        f"Lignes = {n:3d} | "
        f"IDs uniques = {n_ids:3d} | "
        f"Lignes avec ID répété = {n_dupliques:3d}"
    )


audit_unicite("D1", d1_analytique)
audit_unicite("T0", t0_analytique)
audit_unicite("T1", t1_analytique)
audit_unicite("T2", t2_analytique)

D1              | Lignes = 472 | IDs uniques = 472 | Lignes avec ID répété =   0
T0              | Lignes = 305 | IDs uniques = 305 | Lignes avec ID répété =   0
T1              | Lignes = 196 | IDs uniques = 196 | Lignes avec ID répété =   0
T2              | Lignes = 206 | IDs uniques = 206 | Lignes avec ID répété =   0

# Cellule 26 — Recalcul définitif des cohortes

In [35]:
# ============================================================
# CELLULE 26 — Cohortes analytiques définitives
# ============================================================

IDS_D1_CLEAN = set(d1_analytique["_ID_NORM"])
IDS_T0_CLEAN = set(t0_analytique["_ID_NORM"])
IDS_T1_CLEAN = set(t1_analytique["_ID_NORM"])
IDS_T2_CLEAN = set(t2_analytique["_ID_NORM"])


COHORTE_MT0 = (
    IDS_D1_CLEAN
    & IDS_T0_CLEAN
    & IDS_T2_CLEAN
)

COHORTE_MT1 = (
    IDS_D1_CLEAN
    & IDS_T0_CLEAN
    & IDS_T1_CLEAN
    & IDS_T2_CLEAN
)


# Pour comparaison équitable M_T0 vs M_T1 :
COHORTE_COMPARAISON = COHORTE_MT1


resume_cohortes = pd.DataFrame({

    "Cohorte": [
        "D1",
        "T0",
        "T1",
        "T2",
        "M_T0",
        "M_T1",
        "Comparaison M_T0 vs M_T1"
    ],

    "N": [
        len(IDS_D1_CLEAN),
        len(IDS_T0_CLEAN),
        len(IDS_T1_CLEAN),
        len(IDS_T2_CLEAN),
        len(COHORTE_MT0),
        len(COHORTE_MT1),
        len(COHORTE_COMPARAISON)
    ]

})


display(resume_cohortes)

                    Cohorte    N
0                        D1  472
1                        T0  305
2                        T1  196
3                        T2  206
4                      M_T0  128
5                      M_T1  125
6  Comparaison M_T0 vs M_T1  125

#  Cellule 27 — Identifier les 3 apprenants disponibles pour M_T0 mais pas M_T1

In [36]:
# ============================================================
# CELLULE 27 — Différence entre cohortes M_T0 et M_T1
# ============================================================

mt0_sans_t1 = sorted(
    COHORTE_MT0 - COHORTE_MT1
)

print(
    "Apprenants M_T0 absents de M_T1 :",
    len(mt0_sans_t1)
)

print(mt0_sans_t1)

Apprenants M_T0 absents de M_T1 : 3
['DIEG2026-158', 'DIEG2026-288', 'DIEG2026-355']

# Cellule 28 — changer l'interprétation

In [37]:
# ============================================================
# CELLULE 28 — IDs T1/T2 hors plage observée dans D1
# ============================================================

numeros_d1 = (
    d1_analytique["_ID_NORM"]
    .map(numero_id)
    .dropna()
)

MAX_NUM_D1 = int(
    numeros_d1.max()
)


t1_analytique["_NUM_ID"] = (
    t1_analytique["_ID_NORM"]
    .map(numero_id)
)

t2_analytique["_NUM_ID"] = (
    t2_analytique["_ID_NORM"]
    .map(numero_id)
)


t1_hors_plage_d1 = (
    t1_analytique[
        t1_analytique["_NUM_ID"]
        >
        MAX_NUM_D1
    ]
)

t2_hors_plage_d1 = (
    t2_analytique[
        t2_analytique["_NUM_ID"]
        >
        MAX_NUM_D1
    ]
)


print(
    "Maximum numérique observé dans D1 :",
    MAX_NUM_D1
)

print(
    "T1 avec numéro ID > max(D1) :",
    len(t1_hors_plage_d1)
)

print(
    "T2 avec numéro ID > max(D1) :",
    len(t2_hors_plage_d1)
)

print(
    "⚠️ Cette différence numérique ne prouve pas "
    "à elle seule une chronologie postérieure."
)

Maximum numérique observé dans D1 : 472
T1 avec numéro ID > max(D1) : 55
T2 avec numéro ID > max(D1) : 60
⚠️ Cette différence numérique ne prouve pas à elle seule une chronologie postérieure.

# Cellule 29 — supprimer les min/max écrits manuellement

In [38]:
# ============================================================
# CELLULE 29 — Synthèse finale dynamique
# ============================================================

def resume_ids_source(df):

    nums = (
        df["_ID_NORM"]
        .dropna()
        .map(numero_id)
        .dropna()
    )

    return {
        "N":
            df["_ID_NORM"]
            .nunique(),

        "ID_min":
            int(nums.min()),

        "ID_max":
            int(nums.max())
    }


synthese_audit = {

    "D1":
        resume_ids_source(
            d1_analytique
        ),

    "T0":
        resume_ids_source(
            t0_analytique
        ),

    "T1": {
        **resume_ids_source(
            t1_analytique
        ),
        "N_ID_hors_plage_D1":
            len(t1_hors_plage_d1)
    },

    "T2": {
        **resume_ids_source(
            t2_analytique
        ),
        "N_ID_hors_plage_D1":
            len(t2_hors_plage_d1)
    },

    "M_T0": {
        "N":
            len(COHORTE_MT0)
    },

    "M_T1": {
        "N":
            len(COHORTE_MT1)
    },

    "Comparaison_MT0_MT1": {
        "N":
            len(COHORTE_COMPARAISON),

        "principe":
            "Même cohorte et mêmes folds"
    },

    "MT0_sans_T1":
        mt0_sans_t1
}


with open(
    OUTPUT_DIR
    / "synthese_audit_initial.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        synthese_audit,
        f,
        indent=4,
        ensure_ascii=False
    )


print(
    json.dumps(
        synthese_audit,
        indent=4,
        ensure_ascii=False
    )
)

{
    "D1": {
        "N": 472,
        "ID_min": 1,
        "ID_max": 472
    },
    "T0": {
        "N": 305,
        "ID_min": 1,
        "ID_max": 471
    },
    "T1": {
        "N": 196,
        "ID_min": 3,
        "ID_max": 656,
        "N_ID_hors_plage_D1": 55
    },
    "T2": {
        "N": 206,
        "ID_min": 3,
        "ID_max": 656,
        "N_ID_hors_plage_D1": 60
    },
    "M_T0": {
        "N": 128
    },
    "M_T1": {
        "N": 125
    },
    "Comparaison_MT0_MT1": {
        "N": 125,
        "principe": "Même cohorte et mêmes folds"
    },
    "MT0_sans_T1": [
        "DIEG2026-158",
        "DIEG2026-288",
        "DIEG2026-355"
    ]
}

In [39]:
# ============================================================
# CELLULE 30 — Sauvegarde des cohortes
# ============================================================

pd.Series(
    sorted(COHORTE_MT0),
    name="IDENTIFICATION"
).to_csv(
    OUTPUT_DIR / "cohorte_MT0.csv",
    index=False,
    encoding="utf-8-sig"
)


pd.Series(
    sorted(COHORTE_MT1),
    name="IDENTIFICATION"
).to_csv(
    OUTPUT_DIR / "cohorte_MT1.csv",
    index=False,
    encoding="utf-8-sig"
)


pd.Series(
    sorted(COHORTE_COMPARAISON),
    name="IDENTIFICATION"
).to_csv(
    OUTPUT_DIR / "cohorte_comparaison_MT0_MT1.csv",
    index=False,
    encoding="utf-8-sig"
)


print("✅ Cohortes sauvegardées")

✅ Cohortes sauvegardées